"""Pydantic contract for ``layer1_source_extraction_schema.json``.

Layer 1 stores grounded syllabus data plus the minimum provenance required by
the merge stage.  IDs and ``crawl_course_key`` are generated by the pipeline;
they are never inferred by the LLM.
"""

from __future__ import annotations

from typing import Annotated, Any, Literal

from pydantic import BaseModel, BeforeValidator, ConfigDict, Field


def _clean_optional_text(value: Any) -> Any:
    """Strip text and represent blank strings consistently as ``None``."""
    if not isinstance(value, str):
        return value
    cleaned = value.strip()
    return cleaned or None


OptionalText = Annotated[str | None, BeforeValidator(_clean_optional_text)]


class _Layer1Model(BaseModel):
    # Legacy Layer 1 files can contain deprecated fields.  Ignoring them here
    # allows migration, while serialization still emits only the v1.2 contract.
    model_config = ConfigDict(extra="ignore")


class Credits(_Layer1Model):
    total: float | None = None
    theory: float | None = None
    practice: float | None = None
    self_study: float | None = None


class SourceDocument(_Layer1Model):
    source_document_id: OptionalText = None
    crawl_course_key: OptionalText = None


class Course(_Layer1Model):
    course_temp_id: OptionalText = None
    course_code: OptionalText = None
    internal_course_code: OptionalText = None
    name_vi: OptionalText = None
    name_en: OptionalText = None
    credits: Credits = Field(default_factory=Credits)
    department: OptionalText = None
    knowledge_block: OptionalText = None
    education_level: OptionalText = None


class Description(_Layer1Model):
    description_temp_id: OptionalText = None
    text: OptionalText = None


class Clo(_Layer1Model):
    clo_temp_id: OptionalText = None
    clo_code: OptionalText = None
    content: OptionalText = None
    order_index: int | None = None


class Chapter(_Layer1Model):
    chapter_temp_id: OptionalText = None
    chapter_code: OptionalText = None
    title: OptionalText = None
    content_text: OptionalText = None
    order_index: int | None = None


class Lesson(_Layer1Model):
    lesson_temp_id: OptionalText = None
    chapter_ref_temp_id: OptionalText = None
    title: OptionalText = None
    order_index: int | None = None


class ExtractedDocument(_Layer1Model):
    """Complete Layer 1 document.

    Older versions remain readable so existing extraction files can be merged.
    Newly constructed documents always default to schema version 1.2.
    """

    schema_version: Literal["1.0", "1.1", "1.2"] = "1.2"
    stage: Literal["layer_1_source_extraction"] = "layer_1_source_extraction"
    source_document: SourceDocument = Field(default_factory=SourceDocument)
    course: Course
    description: Description = Field(default_factory=Description)
    clos: list[Clo] = Field(default_factory=list)
    chapters: list[Chapter] = Field(default_factory=list)
    lessons: list[Lesson] = Field(default_factory=list)
