"""High-precision structural noise rules for extracted academic records.

The rules deliberately reject only deterministic programme/cohort patterns.
Ambiguous administrative text is retained and reported for review so this
layer cannot silently remove legitimate academic content.
"""

from __future__ import annotations

import re
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from pipeline.extract_course.mo_hinh import Chapter, ExtractedDocument, Lesson


COHORT_PATTERNS = (
    re.compile(r"\b(?:ĐH|CĐ)\s*K\s*\d+\b", re.IGNORECASE),
    re.compile(r"\bcohort\s+(?:K\s*)?\d+\b", re.IGNORECASE),
)
AMBIGUOUS_ADMIN_PATTERN = re.compile(
    r"\b(?:đối tượng áp dụng|chương trình đào tạo|ngành đào tạo|khóa đào tạo|"
    r"training programme|training program|applicable cohort)\b",
    re.IGNORECASE,
)


class _ReportModel(BaseModel):
    model_config = ConfigDict(extra="forbid")


class NoiseReportItem(_ReportModel):
    record_type: Literal["chapter", "lesson"]
    record_id: str
    reason: Literal["programme_cohort_noise", "ambiguous_administrative_text"]
    original_text: str
    action: Literal["rejected", "review_required_kept"]


class ExtractionNoiseReport(_ReportModel):
    schema_version: Literal["1.0"] = "1.0"
    stage: Literal["extraction_noise_validation"] = "extraction_noise_validation"
    source_document_id: str
    items: list[NoiseReportItem] = Field(default_factory=list)


def _has_high_confidence_noise(text: str) -> bool:
    return any(pattern.search(text) for pattern in COHORT_PATTERNS)


def _chapter_text(chapter: Chapter) -> str:
    return " | ".join(
        value.strip()
        for value in (chapter.title, chapter.content_text)
        if isinstance(value, str) and value.strip()
    )


def _lesson_text(lesson: Lesson) -> str:
    return (lesson.title or "").strip()


def apply_lightweight_noise_rules(
    document: ExtractedDocument,
    *,
    enabled: bool = True,
    report_ambiguous: bool = True,
) -> tuple[ExtractedDocument, ExtractionNoiseReport]:
    """Reject certain cohort noise and retain ambiguous records with a report.

    The input document is never mutated. IDs already generated by the pipeline
    are used in report items, so the LLM remains unable to create provenance.
    """
    cleaned = document.model_copy(deep=True)
    source_id = cleaned.source_document.source_document_id or "unknown"
    report = ExtractionNoiseReport(source_document_id=source_id)
    if not enabled:
        return cleaned, report

    retained_chapters: list[Chapter] = []
    for chapter in cleaned.chapters:
        text = _chapter_text(chapter)
        record_id = chapter.chapter_temp_id or "unknown_chapter"
        if text and _has_high_confidence_noise(text):
            report.items.append(
                NoiseReportItem(
                    record_type="chapter",
                    record_id=record_id,
                    reason="programme_cohort_noise",
                    original_text=text,
                    action="rejected",
                )
            )
            continue
        if text and report_ambiguous and AMBIGUOUS_ADMIN_PATTERN.search(text):
            report.items.append(
                NoiseReportItem(
                    record_type="chapter",
                    record_id=record_id,
                    reason="ambiguous_administrative_text",
                    original_text=text,
                    action="review_required_kept",
                )
            )
        retained_chapters.append(chapter)

    retained_lessons: list[Lesson] = []
    for lesson in cleaned.lessons:
        text = _lesson_text(lesson)
        record_id = lesson.lesson_temp_id or "unknown_lesson"
        if text and _has_high_confidence_noise(text):
            report.items.append(
                NoiseReportItem(
                    record_type="lesson",
                    record_id=record_id,
                    reason="programme_cohort_noise",
                    original_text=text,
                    action="rejected",
                )
            )
            continue
        if text and report_ambiguous and AMBIGUOUS_ADMIN_PATTERN.search(text):
            report.items.append(
                NoiseReportItem(
                    record_type="lesson",
                    record_id=record_id,
                    reason="ambiguous_administrative_text",
                    original_text=text,
                    action="review_required_kept",
                )
            )
        retained_lessons.append(lesson)

    cleaned.chapters = retained_chapters
    cleaned.lessons = retained_lessons
    return cleaned, report

