"""Bước 7 — Neo4j Writer.

Sinh câu lệnh Cypher và ghi file .cypher cho quan hệ SUPPORTS_SKILL.

Cypher pattern:
    MATCH (c:Course {course_id: $course_id})
    MATCH (s:Skill {skill_id: $skill_id})
    MERGE (c)-[r:SUPPORTS_SKILL]->(s)
    SET r.evidence = $evidence, r.created_at = timestamp()
"""

from __future__ import annotations

import logging
from pathlib import Path

from ..models.record import SupportSkillRecord

logger = logging.getLogger(__name__)


def generate_cypher(record: SupportSkillRecord) -> str:
    """Sinh câu lệnh Cypher cho 1 record SUPPORTS_SKILL.

    Args:
        record: SupportSkillRecord đã accepted.

    Returns:
        Cypher query string.
    """
    # Escape single quotes
    evidence_text = record.evidence_text.replace("'", "\\'")
    concept = record.support_concept_origin.replace("'", "\\'")

    cypher = (
        f"MATCH (c:Course {{course_id: '{record.course_code}'}})\n"
        f"MATCH (s:Skill {{uri: '{record.esco_uri}'}})\n"
        f"MERGE (c)-[r:SUPPORTS_SKILL]->(s)\n"
        f"SET r.support_concept = '{concept}',\n"
        f"    r.evidence_text = '{evidence_text}',\n"
        f"    r.final_score = {record.final_score:.4f},\n"
        f"    r.review_status = '{record.review_status}',\n"
        f"    r.method = '{record.method}',\n"
        f"    r.created_at = timestamp();\n"
    )
    return cypher


def write_cypher_file(
    records: list[SupportSkillRecord],
    output_dir: str | Path,
    course_code: str,
) -> None:
    """Ghi file .cypher cho 1 course.

    Args:
        records: Danh sách records đã accepted.
        output_dir: Thư mục output gốc.
        course_code: Mã học phần.
    """
    out_path = Path(output_dir)
    cypher_dir = out_path / "_cypher"
    cypher_dir.mkdir(parents=True, exist_ok=True)

    cypher_path = cypher_dir / f"{course_code}.cypher"

    lines = [
        f"// SUPPORTS_SKILL relations for {course_code}",
        f"// Generated by supports_skill_pipeline M5",
        f"// Total relations: {len(records)}",
        "",
    ]

    for record in records:
        lines.append(generate_cypher(record))
        lines.append("")

    with open(cypher_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    logger.info(
        "Written Cypher file: %s (%d relations)",
        cypher_path, len(records),
    )
