// SUPPORTS_SKILL relations for BM6091_BS
// Generated by supports_skill_pipeline M5
// Total relations: 5

MATCH (c:Course {course_id: 'BM6091_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/cef5c0f8-1e40-4c09-b6a7-aa7811849e5d'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'adaptability; collaborative problem solving; ethical judgment',
    r.evidence_text = 'Students will be able to analyze team organizational models, project management tools and methods to achieve goals within constraints of time and resources',
    r.final_score = 0.8055,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'BM6091_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/7111b95d-0ce3-441a-9d92-4c75d05c4388'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'resource optimization; time management',
    r.evidence_text = 'Apply technical tools for time, cost, quality management, and resource allocation (such as network diagrams, PERT, GANTT) to practical project planning and management',
    r.final_score = 0.7681,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'BM6091_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/d5145a9a-602e-40bf-b3e1-f04cf9c3ef86'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'adaptability; leadership mindset',
    r.evidence_text = 'Form an attitude of respect for principles in project management, along with a proper awareness of the role, responsibilities, and professional ethics of a project manager',
    r.final_score = 0.7624,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'BM6091_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/bd698bbe-7003-4508-b422-46c2ff4d5e95'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'strategic thinking',
    r.evidence_text = 'Form an attitude of respect for principles in project management, along with a proper awareness of the role, responsibilities, and professional ethics of a project manager',
    r.final_score = 0.6397,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'BM6091_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/2d140a3a-45a6-4248-80dd-b3760ebc9cc6'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'adaptability; resource optimization; time management',
    r.evidence_text = 'Apply technical tools for time, cost, quality management, and resource allocation (such as network diagrams, PERT, GANTT) to practical project planning and management',
    r.final_score = 0.5744,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();

