// SUPPORTS_SKILL relations for BS6021_BS
// Generated by supports_skill_pipeline M5
// Total relations: 2

MATCH (c:Course {course_id: 'BS6021_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/cef5c0f8-1e40-4c09-b6a7-aa7811849e5d'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'complex problem solving; ethical reasoning; resource management mindset',
    r.evidence_text = 'Enhances awareness and demonstrates personal responsibility in environmental protection and resource conservation in present and future life',
    r.final_score = 0.8077,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'BS6021_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/cdd8b6b2-2fd9-453c-8d62-8a1dc6efcd49'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'evidence-based decision making; systems thinking',
    r.evidence_text = 'Description: The course provides general theoretical foundations on the relationship between humans and the environment',
    r.final_score = 0.6571,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();

