// SUPPORTS_SKILL relations for BS6001_BS
// Generated by supports_skill_pipeline M5
// Total relations: 7

MATCH (c:Course {course_id: 'BS6001_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/8b0f73ff-d36b-4196-bb83-464c3a6ef07d'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'abstract reasoning; mathematical modeling; systemic analysis',
    r.evidence_text = 'Proficiently apply mathematical methods of linear algebra to solve computational problems and practical application problems in the engineering field',
    r.final_score = 0.8267,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'BS6001_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/45f1ae17-c20d-40fc-9307-7d33b6ca9213'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'multidimensional visualization; pattern recognition',
    r.evidence_text = 'Course: Đại số tuyến tính',
    r.final_score = 0.7437,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'BS6001_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/e464363b-8346-421d-9035-52118b76d8c8'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'algorithmic thinking; computational fluency; precision in communication',
    r.evidence_text = 'Develop logical thinking, self-learning and self-research abilities, and a sense of responsibility in applying mathematical tools to solve practical problems',
    r.final_score = 0.7432,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'BS6001_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/33e584f9-ff7a-4979-bfc0-5a3a374a145a'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'systemic analysis',
    r.evidence_text = 'Course: Đại số tuyến tính',
    r.final_score = 0.6668,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'BS6001_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/4134622c-c3fb-4a41-beb6-6d58ba5107db'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'computational fluency; rigorous proof-based thinking',
    r.evidence_text = 'Develop logical thinking, self-learning and self-research abilities, and a sense of responsibility in applying mathematical tools to solve practical problems',
    r.final_score = 0.6298,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'BS6001_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/afda6ca0-7aa8-41ef-ba5e-8dc607839daf'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'multidimensional visualization; systemic analysis',
    r.evidence_text = 'Course: Đại số tuyến tính',
    r.final_score = 0.6255,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'BS6001_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/cdd8b6b2-2fd9-453c-8d62-8a1dc6efcd49'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'systemic analysis',
    r.evidence_text = 'Course: Đại số tuyến tính',
    r.final_score = 0.5878,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();

