// SUPPORTS_SKILL relations for BS6042_BS
// Generated by supports_skill_pipeline M5
// Total relations: 8

MATCH (c:Course {course_id: 'BS6042_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/5b26f08b-88bc-45f0-b901-530d7786466b'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'evidence-based decision making; scientific inquiry',
    r.evidence_text = 'Proficiently solve problems of parameter estimation and statistical hypothesis testing, while applying data collection, processing, and analysis skills for decision-making',
    r.final_score = 0.8565,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'BS6042_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/7b5cce4d-c7fe-4119-b48f-70aa05391787'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'abstract modeling; scientific inquiry',
    r.evidence_text = '- The Mathematical Statistics part introduces estimation problems and statistical hypothesis testing problems',
    r.final_score = 0.7284,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'BS6042_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/4134622c-c3fb-4a41-beb6-6d58ba5107db'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'evidence-based decision making; intellectual rigor; scientific inquiry',
    r.evidence_text = 'Proficiently solve problems of parameter estimation and statistical hypothesis testing, while applying data collection, processing, and analysis skills for decision-making',
    r.final_score = 0.6829,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'BS6042_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/edebd83d-35f6-4ed5-a940-6c203d178c01'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'data literacy; evidence-based decision making',
    r.evidence_text = 'Proficiently solve problems of parameter estimation and statistical hypothesis testing, while applying data collection, processing, and analysis skills for decision-making',
    r.final_score = 0.6765,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'BS6042_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/8b0f73ff-d36b-4196-bb83-464c3a6ef07d'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'critical thinking; evidence-based decision making',
    r.evidence_text = 'Proficiently solve problems of parameter estimation and statistical hypothesis testing, while applying data collection, processing, and analysis skills for decision-making',
    r.final_score = 0.6547,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'BS6042_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/7159e587-c7cb-4ec0-a662-03e1dee2cccb'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'abstract modeling; data literacy; deductive reasoning',
    r.evidence_text = 'Forms and develops logical thinking, carefulness, and precision in solving practical problems related to probability and statistics, creating a basis for studying and researching specialized subjects',
    r.final_score = 0.6000,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'BS6042_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/45f1ae17-c20d-40fc-9307-7d33b6ca9213'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'evidence-based decision making; pattern recognition',
    r.evidence_text = 'Proficiently solve problems of parameter estimation and statistical hypothesis testing, while applying data collection, processing, and analysis skills for decision-making',
    r.final_score = 0.5710,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'BS6042_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/b011c8b4-76e1-4bbc-8bb9-1d205e7b618a'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'evidence-based decision making',
    r.evidence_text = 'Proficiently solve problems of parameter estimation and statistical hypothesis testing, while applying data collection, processing, and analysis skills for decision-making',
    r.final_score = 0.5696,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();

