// SUPPORTS_SKILL relations for BS6018_BS
// Generated by supports_skill_pipeline M5
// Total relations: 4

MATCH (c:Course {course_id: 'BS6018_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/93e65de1-923c-437e-aa5b-e6002967ce71'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'collaborative spirit; empathy',
    r.evidence_text = 'Form a proactive and open attitude',
    r.final_score = 0.7389,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'BS6018_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/123cf7c5-6a3b-419d-be4f-49a6cc020f9f'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'active observation; empathy',
    r.evidence_text = 'Form a proactive and open attitude',
    r.final_score = 0.5687,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'BS6018_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/bd698bbe-7003-4508-b422-46c2ff4d5e95'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'interpersonal sensitivity; negotiation mindset',
    r.evidence_text = 'Course: Giao tiếp trong môi trường làm việc',
    r.final_score = 0.5327,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'BS6018_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/7111b95d-0ce3-441a-9d92-4c75d05c4388'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'critical social awareness; interpersonal sensitivity',
    r.evidence_text = 'Form a proactive and open attitude',
    r.final_score = 0.5258,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();

