// SUPPORTS_SKILL relations for BS6038_BS
// Generated by supports_skill_pipeline M5
// Total relations: 7

MATCH (c:Course {course_id: 'BS6038_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/8b0f73ff-d36b-4196-bb83-464c3a6ef07d'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'logical structuring of arguments; mathematical modeling; systematic problem decomposition',
    r.evidence_text = 'Solve practical engineering problems related to extrema, optimization, and applications of double integrals and line integrals through analytical thinking and computational skills',
    r.final_score = 0.7848,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'BS6038_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/21d2f96d-35f7-4e3f-9745-c533d2dd6e97'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'abstract reasoning; algorithmic thinking; logical structuring of arguments',
    r.evidence_text = 'Develops analytical thinking, computational skills, and the ability to solve practical problems in engineering such as optimization, work computation, force analysis, and multivariable function analysis',
    r.final_score = 0.7570,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'BS6038_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/98a1dec3-8138-4f46-a596-5e2a83b884b9'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'logical structuring of arguments; persistence in complex problem solving; quantitative literacy',
    r.evidence_text = 'Forms a proactive learning attitude, logical thinking, carefulness in computation, and the ability to effectively apply mathematical tools in approaching specialized engineering subjects',
    r.final_score = 0.7207,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'BS6038_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/4134622c-c3fb-4a41-beb6-6d58ba5107db'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'attention to detail; persistence in complex problem solving; quantitative literacy',
    r.evidence_text = 'Course: Giải tích',
    r.final_score = 0.6665,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'BS6038_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/45f1ae17-c20d-40fc-9307-7d33b6ca9213'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'pattern recognition; quantitative literacy',
    r.evidence_text = 'Course: Giải tích',
    r.final_score = 0.6546,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'BS6038_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/d31fab87-2a7d-485c-b699-2901ca294b15'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'algorithmic thinking; logical structuring of arguments; mathematical modeling',
    r.evidence_text = 'Develops analytical thinking, computational skills, and the ability to solve practical problems in engineering such as optimization, work computation, force analysis, and multivariable function analysis',
    r.final_score = 0.6418,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'BS6038_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/5608d5a0-6d5e-43b7-be37-616501729bb4'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'algorithmic thinking; persistence in complex problem solving; quantitative literacy',
    r.evidence_text = 'Develops analytical thinking, computational skills, and the ability to solve practical problems in engineering such as optimization, work computation, force analysis, and multivariable function analysis',
    r.final_score = 0.6038,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();

