// SUPPORTS_SKILL relations for BS6054_BS
// Generated by supports_skill_pipeline M5
// Total relations: 4

MATCH (c:Course {course_id: 'BS6054_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/5b26f08b-88bc-45f0-b901-530d7786466b'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'abstract conceptualization; scientific methodology',
    r.evidence_text = 'Form a scientific worldview, logical thinking, carefulness, and honesty in the process of collecting and processing experimental data, along with a sense of responsibility in study and research',
    r.final_score = 0.8260,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'BS6054_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/4134622c-c3fb-4a41-beb6-6d58ba5107db'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'analytical rigor; precision and accuracy; scientific methodology',
    r.evidence_text = 'Form a scientific worldview, logical thinking, carefulness, and honesty in the process of collecting and processing experimental data, along with a sense of responsibility in study and research',
    r.final_score = 0.6981,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'BS6054_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/7b5cce4d-c7fe-4119-b48f-70aa05391787'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'mathematical modeling; scientific methodology',
    r.evidence_text = 'Form a scientific worldview, logical thinking, carefulness, and honesty in the process of collecting and processing experimental data, along with a sense of responsibility in study and research',
    r.final_score = 0.6963,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'BS6054_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/7159e587-c7cb-4ec0-a662-03e1dee2cccb'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'experimental design mindset; technical documentation',
    r.evidence_text = 'Form a scientific worldview, logical thinking, carefulness, and honesty in the process of collecting and processing experimental data, along with a sense of responsibility in study and research',
    r.final_score = 0.6754,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();

