// SUPPORTS_SKILL relations for BS6002_BS
// Generated by supports_skill_pipeline M5
// Total relations: 4

MATCH (c:Course {course_id: 'BS6002_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/68ef0e4d-5542-4e64-84f4-752cce5a3c22'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'critical analysis of assumptions; mathematical modeling',
    r.evidence_text = 'Course: Giải tích',
    r.final_score = 0.6651,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'BS6002_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/8b0f73ff-d36b-4196-bb83-464c3a6ef07d'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'abstract thinking; mathematical modeling; quantitative literacy',
    r.evidence_text = 'Course: Giải tích',
    r.final_score = 0.6338,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'BS6002_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/45f1ae17-c20d-40fc-9307-7d33b6ca9213'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'pattern recognition; quantitative literacy',
    r.evidence_text = 'Course: Giải tích',
    r.final_score = 0.6270,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'BS6002_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/98a1dec3-8138-4f46-a596-5e2a83b884b9'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'mathematical modeling; persistence in problem solving; systematic approach to complexity',
    r.evidence_text = 'Course: Giải tích',
    r.final_score = 0.6038,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();

