// SUPPORTS_SKILL relations for BS6019_BS
// Generated by supports_skill_pipeline M5
// Total relations: 5

MATCH (c:Course {course_id: 'BS6019_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/4134622c-c3fb-4a41-beb6-6d58ba5107db'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'evidence-based reasoning; information literacy; synthesizing complex information',
    r.evidence_text = 'CLO: Explain the core concepts of methodology, the scientific research process, and basic qualitative and quantitative research methods',
    r.final_score = 0.7909,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'BS6019_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/7111b95d-0ce3-441a-9d92-4c75d05c4388'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'project planning',
    r.evidence_text = 'Proficiently apply the steps in the process to build a research proposal, process and analyze data, write reports, and present scientific research results',
    r.final_score = 0.7306,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'BS6019_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/979cf728-896f-4f2c-8fa8-2698ca0d4930'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'academic integrity; structured communication',
    r.evidence_text = 'Enhancing self-study capacity, self-research capability, critical thinking, and a sense of responsibility in the process of carrying out academic activities and scientific research',
    r.final_score = 0.7163,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'BS6019_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/74e49482-75e8-4637-bdb1-fff868d02f7a'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'academic integrity; structured communication; time management',
    r.evidence_text = 'Enhancing self-study capacity, self-research capability, critical thinking, and a sense of responsibility in the process of carrying out academic activities and scientific research',
    r.final_score = 0.6763,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'BS6019_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/7159e587-c7cb-4ec0-a662-03e1dee2cccb'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'objective analysis; project planning',
    r.evidence_text = 'Proficiently apply the steps in the process to build a research proposal, process and analyze data, write reports, and present scientific research results',
    r.final_score = 0.6438,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();

