// SUPPORTS_SKILL relations for BS6051_BS
// Generated by supports_skill_pipeline M5
// Total relations: 4

MATCH (c:Course {course_id: 'BS6051_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/123cf7c5-6a3b-419d-be4f-49a6cc020f9f'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'effective communication; pattern recognition',
    r.evidence_text = 'and content-form relationships in art',
    r.final_score = 0.7445,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'BS6051_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/aba1f05b-f312-47d8-be71-7c574134de8f'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'effective communication',
    r.evidence_text = 'and content-form relationships in art',
    r.final_score = 0.7042,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'BS6051_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/afda6ca0-7aa8-41ef-ba5e-8dc607839daf'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'multidisciplinary synthesis; pattern recognition',
    r.evidence_text = 'artistic imagery',
    r.final_score = 0.6003,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'BS6051_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/cef5c0f8-1e40-4c09-b6a7-aa7811849e5d'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'critical thinking; historical contextualization',
    r.evidence_text = 'and content-form relationships in art',
    r.final_score = 0.5185,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();

