// SUPPORTS_SKILL relations for BS6020_BS
// Generated by supports_skill_pipeline M5
// Total relations: 5

MATCH (c:Course {course_id: 'BS6020_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/cef5c0f8-1e40-4c09-b6a7-aa7811849e5d'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'professional ethics',
    r.evidence_text = 'It helps students proactively engage in the professional world after graduation',
    r.final_score = 0.7111,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'BS6020_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/bd698bbe-7003-4508-b422-46c2ff4d5e95'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'negotiation strategy; regulatory compliance mindset',
    r.evidence_text = 'Apply knowledge of labor contracts, social dialogue, collective bargaining, and the job interview process to solve practical issues regarding employment and labor relations',
    r.final_score = 0.6173,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'BS6020_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/5c606d18-6404-4047-b235-350f18e11827'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'legal literacy; negotiation strategy; professional ethics',
    r.evidence_text = 'Apply knowledge of labor contracts, social dialogue, collective bargaining, and the job interview process to solve practical issues regarding employment and labor relations',
    r.final_score = 0.6141,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'BS6020_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/cdd8b6b2-2fd9-453c-8d62-8a1dc6efcd49'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'professional ethics; systems thinking',
    r.evidence_text = 'It helps students proactively engage in the professional world after graduation',
    r.final_score = 0.5984,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'BS6020_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/8b0f73ff-d36b-4196-bb83-464c3a6ef07d'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'analytical reasoning; professional ethics; social awareness',
    r.evidence_text = 'It helps students proactively engage in the professional world after graduation',
    r.final_score = 0.5911,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();

