// SUPPORTS_SKILL relations for IT6208
// Generated by supports_skill_pipeline M5
// Total relations: 8

MATCH (c:Course {course_id: 'IT6208'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/bec4359e-cb92-468f-a997-8fb28e32fba9'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'project management',
    r.evidence_text = 'being proactive in organizing, managing progress, solution quality, and making professional decisions within the scope of the assigned project',
    r.final_score = 0.9009,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'IT6208'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/d5a59ca8-2e91-472e-8571-d12ce4478679'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'project management; strategic planning',
    r.evidence_text = 'being proactive in organizing, managing progress, solution quality, and making professional decisions within the scope of the assigned project',
    r.final_score = 0.8479,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'IT6208'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/7111b95d-0ce3-441a-9d92-4c75d05c4388'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'project management; technical documentation',
    r.evidence_text = 'being proactive in organizing, managing progress, solution quality, and making professional decisions within the scope of the assigned project',
    r.final_score = 0.8351,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'IT6208'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/0a9acb6b-1139-4be9-b431-3a80a959f2f4'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'project management; technical documentation',
    r.evidence_text = 'being proactive in organizing, managing progress, solution quality, and making professional decisions within the scope of the assigned project',
    r.final_score = 0.7863,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'IT6208'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/94dd823c-148e-4614-a6e8-99249b16357d'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'project management',
    r.evidence_text = 'being proactive in organizing, managing progress, solution quality, and making professional decisions within the scope of the assigned project',
    r.final_score = 0.7727,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'IT6208'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/da6393d5-a53c-4863-abc7-51f36281d74e'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'project management; technical documentation',
    r.evidence_text = 'being proactive in organizing, managing progress, solution quality, and making professional decisions within the scope of the assigned project',
    r.final_score = 0.7625,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'IT6208'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/4134622c-c3fb-4a41-beb6-6d58ba5107db'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'professional communication; professional ethics',
    r.evidence_text = 'while deeply understanding the principles of technology transfer, operation, and management of information systems in a practical context',
    r.final_score = 0.6772,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'IT6208'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/6eff134b-e34f-4d6e-a6e8-5e47cf2228d0'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'risk assessment',
    r.evidence_text = 'Manage information systems at a basic level, including the management of functions, data, operations, and risks during utilization',
    r.final_score = 0.5944,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();

