// SUPPORTS_SKILL relations for IT6204
// Generated by supports_skill_pipeline M5
// Total relations: 6

MATCH (c:Course {course_id: 'IT6204'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/7111b95d-0ce3-441a-9d92-4c75d05c4388'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'project management mindset; stakeholder communication',
    r.evidence_text = 'Develop a sense of responsibility and professional ethics in performing system analysis and design activities',
    r.final_score = 0.8309,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'IT6204'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/cdd8b6b2-2fd9-453c-8d62-8a1dc6efcd49'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'iterative refinement; systems thinking',
    r.evidence_text = 'Course: System Analysis and Design',
    r.final_score = 0.6898,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'IT6204'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/94dd823c-148e-4614-a6e8-99249b16357d'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'iterative refinement; project management mindset',
    r.evidence_text = 'Develop a sense of responsibility and professional ethics in performing system analysis and design activities',
    r.final_score = 0.6699,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'IT6204'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/ed1d8bd4-cd2a-4c64-b665-56d70651026c'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'abstract modeling; project management mindset; systems thinking',
    r.evidence_text = 'Course: System Analysis and Design',
    r.final_score = 0.6206,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'IT6204'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/09f2f811-a3fb-4de3-a70f-6420a6935575'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'iterative refinement; project management mindset; systems thinking',
    r.evidence_text = 'Course: System Analysis and Design',
    r.final_score = 0.5693,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'IT6204'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/83218cac-3599-417e-93d2-26013cdccd98'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'abstract modeling; strategic planning; systems thinking',
    r.evidence_text = 'Course: System Analysis and Design',
    r.final_score = 0.5525,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();

