// SUPPORTS_SKILL relations for IT6207
// Generated by supports_skill_pipeline M5
// Total relations: 7

MATCH (c:Course {course_id: 'IT6207'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/5c606d18-6404-4047-b235-350f18e11827'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'cross-functional collaboration; verbal and written professional communication',
    r.evidence_text = 'develop teamwork and professional communication skills',
    r.final_score = 0.8493,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'IT6207'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/e9575f7f-053a-439e-8074-f93df3334e92'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'ethical decision-making; initiative and proactivity',
    r.evidence_text = 'Evaluate and select appropriate behavior in professional situations based on professional ethics principles and social standards in the field of information technology',
    r.final_score = 0.7413,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'IT6207'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/ec6df9cb-be92-4027-80fa-83b70aabce58'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'cross-functional collaboration; initiative and proactivity',
    r.evidence_text = 'develop teamwork and professional communication skills',
    r.final_score = 0.6641,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'IT6207'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/2d140a3a-45a6-4248-80dd-b3760ebc9cc6'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'initiative and proactivity; organizational navigation; time management',
    r.evidence_text = 'CLO: Determine the role and professional responsibilities of an Information Systems professional and successfully complete assigned tasks when participating in practical activities at an enterprise',
    r.final_score = 0.6440,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'IT6207'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/cef5c0f8-1e40-4c09-b6a7-aa7811849e5d'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'ethical decision-making; initiative and proactivity',
    r.evidence_text = 'Evaluate and select appropriate behavior in professional situations based on professional ethics principles and social standards in the field of information technology',
    r.final_score = 0.6371,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'IT6207'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/7111b95d-0ce3-441a-9d92-4c75d05c4388'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'initiative and proactivity; time management',
    r.evidence_text = 'while raising awareness of legal regulations, ethical standards, and professional responsibility in practice',
    r.final_score = 0.5906,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'IT6207'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/89f6560b-2194-45c9-9ece-d33049a73eef'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'professional networking; verbal and written professional communication',
    r.evidence_text = 'develop teamwork and professional communication skills',
    r.final_score = 0.5729,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();

