// SUPPORTS_SKILL relations for IT6203_BS
// Generated by supports_skill_pipeline M5
// Total relations: 3

MATCH (c:Course {course_id: 'IT6203_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/89f6560b-2194-45c9-9ece-d33049a73eef'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'abstraction of hardware layers; concurrency awareness; professional ethics in computing',
    r.evidence_text = 'Course: Nguyên lý hệ điều hành',
    r.final_score = 0.6886,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'IT6203_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/4134622c-c3fb-4a41-beb6-6d58ba5107db'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'professional ethics in computing; understanding of system-level constraints',
    r.evidence_text = 'Course: Nguyên lý hệ điều hành',
    r.final_score = 0.6133,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'IT6203_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/7b5cce4d-c7fe-4119-b48f-70aa05391787'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'critical evaluation of trade-offs; professional ethics in computing',
    r.evidence_text = 'Course: Nguyên lý hệ điều hành',
    r.final_score = 0.5416,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();

