// SUPPORTS_SKILL relations for IT6217_BS
// Generated by supports_skill_pipeline M5
// Total relations: 5

MATCH (c:Course {course_id: 'IT6217_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/89f6560b-2194-45c9-9ece-d33049a73eef'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'academic discipline',
    r.evidence_text = 'Course: Nhập môn về kỹ thuật',
    r.final_score = 0.8263,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'IT6217_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/5b26f08b-88bc-45f0-b901-530d7786466b'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'academic discipline; critical self-reflection; interdisciplinary communication',
    r.evidence_text = 'Course: Nhập môn về kỹ thuật',
    r.final_score = 0.7697,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'IT6217_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/cef5c0f8-1e40-4c09-b6a7-aa7811849e5d'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'academic discipline; collaborative problem solving; ethical reasoning',
    r.evidence_text = 'Clearly define professional responsibilities based on ethical and legal standards in the field of information technology',
    r.final_score = 0.7691,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'IT6217_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/7111b95d-0ce3-441a-9d92-4c75d05c4388'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'academic discipline; adaptability; professional accountability',
    r.evidence_text = 'Clearly define professional responsibilities based on ethical and legal standards in the field of information technology',
    r.final_score = 0.6494,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'IT6217_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/e9575f7f-053a-439e-8074-f93df3334e92'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'ethical reasoning; professional identity formation',
    r.evidence_text = 'Clearly define professional responsibilities based on ethical and legal standards in the field of information technology',
    r.final_score = 0.6024,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();

