// SUPPORTS_SKILL relations for IT6205
// Generated by supports_skill_pipeline M5
// Total relations: 8

MATCH (c:Course {course_id: 'IT6205'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/bec4359e-cb92-468f-a997-8fb28e32fba9'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'critical self-reflection; project management',
    r.evidence_text = 'Learners deploy an entire information system or an IT/engineering technology project in organizations and enterprises',
    r.final_score = 0.7936,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'IT6205'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/e9575f7f-053a-439e-8074-f93df3334e92'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'ethical decision-making; technical documentation standards',
    r.evidence_text = 'evaluate situations based on legal regulations and professional ethics',
    r.final_score = 0.7452,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'IT6205'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/94dd823c-148e-4614-a6e8-99249b16357d'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'problem-solving under constraints; project management',
    r.evidence_text = 'CLO: Design or analyze a product/service/technology/solution blueprint for a practical problem and execute tasks meeting the requirements',
    r.final_score = 0.7039,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'IT6205'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/327d15c8-29ff-4ad4-a4fe-6536d777a45f'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'technical documentation standards',
    r.evidence_text = 'Clearly define professional responsibilities',
    r.final_score = 0.6458,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'IT6205'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/cef5c0f8-1e40-4c09-b6a7-aa7811849e5d'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'ethical decision-making; technical documentation standards',
    r.evidence_text = 'evaluate situations based on legal regulations and professional ethics',
    r.final_score = 0.6234,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'IT6205'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/2d140a3a-45a6-4248-80dd-b3760ebc9cc6'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'business acumen; stakeholder management; technical documentation standards',
    r.evidence_text = 'Objectives: Equip learners with practical knowledge at organizations and enterprises',
    r.final_score = 0.5191,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'IT6205'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/93e65de1-923c-437e-aa5b-e6002967ce71'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'corporate culture navigation; interpersonal collaboration',
    r.evidence_text = 'Objectives: Equip learners with practical knowledge at organizations and enterprises',
    r.final_score = 0.5170,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'IT6205'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/9ce670ec-318c-4a91-9179-03437db728dc'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'technical documentation standards',
    r.evidence_text = 'Clearly define professional responsibilities',
    r.final_score = 0.4987,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();

