// SUPPORTS_SKILL relations for IT6206
// Generated by supports_skill_pipeline M5
// Total relations: 9

MATCH (c:Course {course_id: 'IT6206'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/bec4359e-cb92-468f-a997-8fb28e32fba9'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'project management; systemic thinking',
    r.evidence_text = 'Learners apply comprehensive knowledge to build software or solve practical problems based on information technology solutions',
    r.final_score = 0.7939,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'IT6206'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/d5a59ca8-2e91-472e-8571-d12ce4478679'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'problem decomposition; project management',
    r.evidence_text = 'Learners apply comprehensive knowledge to build software or solve practical problems based on information technology solutions',
    r.final_score = 0.7510,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'IT6206'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/0a9acb6b-1139-4be9-b431-3a80a959f2f4'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'problem decomposition; project management',
    r.evidence_text = 'Learners apply comprehensive knowledge to build software or solve practical problems based on information technology solutions',
    r.final_score = 0.7331,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'IT6206'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/4d30ad07-9e39-4899-81dd-02b280f162f9'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'resourcefulness; systemic thinking',
    r.evidence_text = 'Course: Graduation Thesis',
    r.final_score = 0.7241,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'IT6206'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/7111b95d-0ce3-441a-9d92-4c75d05c4388'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'project management; stakeholder management',
    r.evidence_text = 'Learners apply comprehensive knowledge to build software or solve practical problems based on information technology solutions',
    r.final_score = 0.7075,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'IT6206'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/da6393d5-a53c-4863-abc7-51f36281d74e'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'problem decomposition; project management',
    r.evidence_text = 'Learners apply comprehensive knowledge to build software or solve practical problems based on information technology solutions',
    r.final_score = 0.6744,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'IT6206'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/94dd823c-148e-4614-a6e8-99249b16357d'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'problem decomposition; project management',
    r.evidence_text = 'Learners apply comprehensive knowledge to build software or solve practical problems based on information technology solutions',
    r.final_score = 0.6504,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'IT6206'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/79f24a62-7718-46e1-9b41-37be0560a5ca'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'resilience; stakeholder management',
    r.evidence_text = 'Learners are proactive and receptive in learning, possessing self-discipline and a serious learning attitude',
    r.final_score = 0.6354,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'IT6206'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/0ffdb6ac-03b5-4f1c-bfcc-3d9cb874fdf9'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'ethical decision-making; systemic thinking',
    r.evidence_text = 'Course: Graduation Thesis',
    r.final_score = 0.5342,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();

