// SUPPORTS_SKILL relations for IT6202_BS
// Generated by supports_skill_pipeline M5
// Total relations: 2

MATCH (c:Course {course_id: 'IT6202_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/cdd8b6b2-2fd9-453c-8d62-8a1dc6efcd49'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'systems thinking; technological adaptability',
    r.evidence_text = 'Enhance the spirit of self-study, proactively update knowledge of new hardware technologies, and maintain responsibility for adhering to the principles of safe and efficient computer system design',
    r.final_score = 0.7551,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'IT6202_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/397da142-ab35-48fe-b154-7c38f447adfb'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'systems thinking; technological adaptability',
    r.evidence_text = 'Enhance the spirit of self-study, proactively update knowledge of new hardware technologies, and maintain responsibility for adhering to the principles of safe and efficient computer system design',
    r.final_score = 0.5509,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();

