// SUPPORTS_SKILL relations for IT6218
// Generated by supports_skill_pipeline M5
// Total relations: 5

MATCH (c:Course {course_id: 'IT6218'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/ccdbd9bb-4faf-403c-a968-e8bf487f8a53'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'complex system architecture understanding; process optimization; resource management',
    r.evidence_text = 'Use a Database Management System for information security, user administration, data backup, and recovery',
    r.final_score = 0.7993,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'IT6218'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/2450c3b3-e78e-435b-b84d-e05d984e71dc'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'complex system architecture understanding; structured thinking',
    r.evidence_text = 'Course: Database Management System (DBMS)',
    r.final_score = 0.6701,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'IT6218'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/4134622c-c3fb-4a41-beb6-6d58ba5107db'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'complex system architecture understanding; data integrity awareness',
    r.evidence_text = 'Use a Database Management System for information security, user administration, data backup, and recovery',
    r.final_score = 0.6080,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'IT6218'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/43ae58b9-5e56-4524-b45a-b422777a0576'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'complex system architecture understanding; resource management',
    r.evidence_text = 'Use a Database Management System for information security, user administration, data backup, and recovery',
    r.final_score = 0.5561,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'IT6218'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/397da142-ab35-48fe-b154-7c38f447adfb'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'complex system architecture understanding; process optimization; structured thinking',
    r.evidence_text = 'Course: Database Management System (DBMS)',
    r.final_score = 0.5316,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();

