// SUPPORTS_SKILL relations for SC6019
// Generated by supports_skill_pipeline M5
// Total relations: 8

MATCH (c:Course {course_id: 'SC6019'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/33d49d4f-31ec-473f-9b8a-b555aa5116bb'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'adaptability to evolving technologies; iterative problem solving',
    r.evidence_text = 'Apply machine learning theory in creating computer-based solutions',
    r.final_score = 0.8058,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6019'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/2450c3b3-e78e-435b-b84d-e05d984e71dc'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'pattern recognition; system architecture mindset',
    r.evidence_text = 'Course: Machine Learning',
    r.final_score = 0.7631,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6019'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/8369c2d6-c100-4cf6-bd83-9668d8678433'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'adaptability to evolving technologies; pattern recognition',
    r.evidence_text = 'Course: Machine Learning',
    r.final_score = 0.6518,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6019'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/7159e587-c7cb-4ec0-a662-03e1dee2cccb'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'experimental design; hypothesis testing',
    r.evidence_text = 'On this basis, students can design learning systems and conduct deeper research into specific problems such as diagnosis and forecasting',
    r.final_score = 0.6336,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6019'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/ed1d8bd4-cd2a-4c64-b665-56d70651026c'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'complex system debugging; experimental design',
    r.evidence_text = 'On this basis, students can design learning systems and conduct deeper research into specific problems such as diagnosis and forecasting',
    r.final_score = 0.6203,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6019'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/45f1ae17-c20d-40fc-9307-7d33b6ca9213'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'pattern recognition',
    r.evidence_text = 'Course: Machine Learning',
    r.final_score = 0.6180,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6019'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/8ff015a0-98ea-4d80-a23e-1f68110a919e'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'complex system debugging; experimental design; system architecture mindset',
    r.evidence_text = 'On this basis, students can design learning systems and conduct deeper research into specific problems such as diagnosis and forecasting',
    r.final_score = 0.5722,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6019'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/21d2f96d-35f7-4e3f-9745-c533d2dd6e97'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'complex system debugging; computational thinking; critical evaluation of evidence',
    r.evidence_text = 'Apply machine learning theory in creating computer-based solutions',
    r.final_score = 0.5580,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();

