// SUPPORTS_SKILL relations for SC6014
// Generated by supports_skill_pipeline M5
// Total relations: 4

MATCH (c:Course {course_id: 'SC6014'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/ccdbd9bb-4faf-403c-a968-e8bf487f8a53'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'accountability; professional communication; resource management',
    r.evidence_text = 'and gain skills in planning and operating a basic information systems project',
    r.final_score = 0.7045,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6014'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/7111b95d-0ce3-441a-9d92-4c75d05c4388'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'problem framing; resource management; time management',
    r.evidence_text = 'and gain skills in planning and operating a basic information systems project',
    r.final_score = 0.7041,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6014'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/3ce1fe19-7f9e-4070-941d-651673a5693b'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'accountability; strategic decision-making',
    r.evidence_text = 'and gain skills in planning and operating a basic information systems project',
    r.final_score = 0.5945,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6014'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/ec6df9cb-be92-4027-80fa-83b70aabce58'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'interdisciplinary synthesis; problem framing',
    r.evidence_text = 'Implement teamwork in a project environment to assign tasks, coordinate execution, and complete a basic-level information system',
    r.final_score = 0.4988,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();

