// SUPPORTS_SKILL relations for SC6016
// Generated by supports_skill_pipeline M5
// Total relations: 8

MATCH (c:Course {course_id: 'SC6016'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/7111b95d-0ce3-441a-9d92-4c75d05c4388'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'project management; resourcefulness',
    r.evidence_text = 'Ability to apply foundational knowledge and techniques of the discipline to design IT solutions',
    r.final_score = 0.8031,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6016'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/bec4359e-cb92-468f-a997-8fb28e32fba9'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'iterative development mindset; project management',
    r.evidence_text = 'Ability to apply foundational knowledge and techniques of the discipline to design IT solutions',
    r.final_score = 0.7969,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6016'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/94dd823c-148e-4614-a6e8-99249b16357d'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'collaborative problem solving; project management',
    r.evidence_text = 'Ability to apply foundational knowledge and techniques of the discipline to design IT solutions',
    r.final_score = 0.6853,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6016'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/cdd8b6b2-2fd9-453c-8d62-8a1dc6efcd49'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'collaborative problem solving; systems thinking',
    r.evidence_text = 'Ability to apply foundational knowledge and techniques of the discipline to design IT solutions',
    r.final_score = 0.6729,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6016'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/09f2f811-a3fb-4de3-a70f-6420a6935575'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'collaborative problem solving; iterative development mindset; systems thinking',
    r.evidence_text = 'Ability to apply foundational knowledge and techniques of the discipline to design IT solutions',
    r.final_score = 0.6377,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6016'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/24c200e5-be20-4370-a137-ab53797f3a17'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'collaborative problem solving; iterative development mindset; systems thinking',
    r.evidence_text = 'Ability to apply foundational knowledge and techniques of the discipline to design IT solutions',
    r.final_score = 0.6265,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6016'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/327d15c8-29ff-4ad4-a4fe-6536d777a45f'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'documentation discipline; resourcefulness',
    r.evidence_text = 'Course: Foundation Project',
    r.final_score = 0.6003,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6016'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/89f6560b-2194-45c9-9ece-d33049a73eef'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'documentation discipline; professional accountability',
    r.evidence_text = 'Course: Foundation Project',
    r.final_score = 0.5856,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();

