// SUPPORTS_SKILL relations for SC6013
// Generated by supports_skill_pipeline M5
// Total relations: 6

MATCH (c:Course {course_id: 'SC6013'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/bec4359e-cb92-468f-a997-8fb28e32fba9'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'resource allocation mindset; systems thinking; time management',
    r.evidence_text = 'apply professional knowledge and teamwork skills to plan, organize, coordinate, and solve practical problems in information technology project management',
    r.final_score = 0.8029,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6013'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/94dd823c-148e-4614-a6e8-99249b16357d'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'resource allocation mindset; stakeholder management; time management',
    r.evidence_text = 'master traditional project management processes: initiation, planning, execution, monitoring and controlling, and closing',
    r.final_score = 0.7096,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6013'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/d5145a9a-602e-40bf-b3e1-f04cf9c3ef86'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'leadership and delegation; stakeholder management',
    r.evidence_text = 'master traditional project management processes: initiation, planning, execution, monitoring and controlling, and closing',
    r.final_score = 0.6847,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6013'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/6eff134b-e34f-4d6e-a6e8-5e47cf2228d0'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'decision-making under uncertainty; risk assessment intuition',
    r.evidence_text = 'capable of identifying and proposing solutions to control project risks, costs, time, and quality',
    r.final_score = 0.6782,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6013'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/7111b95d-0ce3-441a-9d92-4c75d05c4388'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'resource allocation mindset; stakeholder management; time management',
    r.evidence_text = 'master traditional project management processes: initiation, planning, execution, monitoring and controlling, and closing',
    r.final_score = 0.6628,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6013'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/d5a59ca8-2e91-472e-8571-d12ce4478679'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'leadership and delegation; stakeholder management; time management',
    r.evidence_text = 'master traditional project management processes: initiation, planning, execution, monitoring and controlling, and closing',
    r.final_score = 0.6517,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();

