// SUPPORTS_SKILL relations for SC6218
// Generated by supports_skill_pipeline M5
// Total relations: 8

MATCH (c:Course {course_id: 'SC6218'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/bec4359e-cb92-468f-a997-8fb28e32fba9'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'project management; resource optimization',
    r.evidence_text = 'Course: Game application development',
    r.final_score = 0.7558,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6218'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/94dd823c-148e-4614-a6e8-99249b16357d'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'project management; user experience empathy',
    r.evidence_text = 'Course: Game application development',
    r.final_score = 0.6630,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6218'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/c7cc6dc5-d56b-4323-8e5c-47c4022f615f'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'quality assurance mindset',
    r.evidence_text = 'Deploy, evaluate, and launch game products into the real world',
    r.final_score = 0.6561,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6218'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/d5a59ca8-2e91-472e-8571-d12ce4478679'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'project management; quality assurance mindset',
    r.evidence_text = 'Course: Game application development',
    r.final_score = 0.6469,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6218'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/0a9acb6b-1139-4be9-b431-3a80a959f2f4'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'adaptability to new technologies; project management',
    r.evidence_text = 'Deploy, evaluate, and launch game products into the real world',
    r.final_score = 0.5932,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6218'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/ed1d8bd4-cd2a-4c64-b665-56d70651026c'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'project management; quality assurance mindset; systems thinking',
    r.evidence_text = 'Objectives: Equips learners with foundational knowledge of processes for building and developing game applications',
    r.final_score = 0.5632,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6218'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/da6393d5-a53c-4863-abc7-51f36281d74e'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'adaptability to new technologies; project management',
    r.evidence_text = 'Deploy, evaluate, and launch game products into the real world',
    r.final_score = 0.5502,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6218'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/de0be6e8-644c-4cc9-9c8d-925dd98dda56'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'adaptability to new technologies; presentation and communication skills; systems thinking',
    r.evidence_text = 'Learners design and complete a 2D game product',
    r.final_score = 0.5392,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();

