// SUPPORTS_SKILL relations for SC6228
// Generated by supports_skill_pipeline M5
// Total relations: 2

MATCH (c:Course {course_id: 'SC6228'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/f0393af3-bcd9-41af-a36e-0cfb83b60081'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'problem-solving under constraints; resource management',
    r.evidence_text = 'System Administration: Having the ability to deploy websites from a practice environment to the internet (Hosting/Domain) and manage data storage',
    r.final_score = 0.5679,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6228'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/98a1dec3-8138-4f46-a596-5e2a83b884b9'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'business process mapping; strategic decision making',
    r.evidence_text = 'Commercial Operations: Knowing how to manage product categories, process orders, and handle customer feedback professionally',
    r.final_score = 0.5432,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();

