// SUPPORTS_SKILL relations for SC6237
// Generated by supports_skill_pipeline M5
// Total relations: 7

MATCH (c:Course {course_id: 'SC6237'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/7111b95d-0ce3-441a-9d92-4c75d05c4388'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'project management mindset; technical adaptability',
    r.evidence_text = 'work independently or in teams to execute data analysis projects',
    r.final_score = 0.8325,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6237'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/98a1dec3-8138-4f46-a596-5e2a83b884b9'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'collaborative problem solving; data-driven storytelling; systematic troubleshooting',
    r.evidence_text = 'work independently or in teams to execute data analysis projects',
    r.final_score = 0.7124,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6237'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/edebd83d-35f6-4ed5-a940-6c203d178c01'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'evidence-based decision making',
    r.evidence_text = 'take responsibility for the quality and accuracy of analysis results',
    r.final_score = 0.6725,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6237'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/94dd823c-148e-4614-a6e8-99249b16357d'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'data-driven storytelling; project management mindset',
    r.evidence_text = 'work independently or in teams to execute data analysis projects',
    r.final_score = 0.6529,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6237'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/7b5cce4d-c7fe-4119-b48f-70aa05391787'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'data-driven storytelling; information synthesis',
    r.evidence_text = 'Objectives: explain basic concepts of data, big data, and big data analytics',
    r.final_score = 0.5455,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6237'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/7159e587-c7cb-4ec0-a662-03e1dee2cccb'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'problem decomposition; project management mindset',
    r.evidence_text = 'work independently or in teams to execute data analysis projects',
    r.final_score = 0.5420,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6237'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/fecf8a0d-62c4-4e71-9b03-0f4fc2ad7bf5'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'evidence-based decision making; technical adaptability',
    r.evidence_text = 'take responsibility for the quality and accuracy of analysis results',
    r.final_score = 0.5216,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();

