// SUPPORTS_SKILL relations for SC6220
// Generated by supports_skill_pipeline M5
// Total relations: 9

MATCH (c:Course {course_id: 'SC6220'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/24c200e5-be20-4370-a137-ab53797f3a17'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'adaptability to new environments; project management; version control mindset',
    r.evidence_text = 'readiness to adapt and collaborate in a global software development environment',
    r.final_score = 0.8287,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6220'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/bec4359e-cb92-468f-a997-8fb28e32fba9'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'ethical decision-making; project management',
    r.evidence_text = 'build a sense of strict compliance with regulations on intellectual property and professional ethics',
    r.final_score = 0.8260,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6220'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/7111b95d-0ce3-441a-9d92-4c75d05c4388'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'adaptability to new environments; project management',
    r.evidence_text = 'readiness to adapt and collaborate in a global software development environment',
    r.final_score = 0.8172,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6220'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/93e65de1-923c-437e-aa5b-e6002967ce71'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'collaborative communication; technical documentation literacy',
    r.evidence_text = 'Ability to research documentation, proficiency in planning, and application of acquired knowledge to deploy open-source software development solutions',
    r.final_score = 0.7930,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6220'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/94dd823c-148e-4614-a6e8-99249b16357d'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'cross-cultural teamwork; project management',
    r.evidence_text = 'Ability to research documentation, proficiency in planning, and application of acquired knowledge to deploy open-source software development solutions',
    r.final_score = 0.6572,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6220'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/b16200f4-4f39-4b8b-aa9d-3568054d6bdb'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'critical evaluation of external resources; project management; version control mindset',
    r.evidence_text = 'Objectives: Explain the principles of open-source resource exploitation',
    r.final_score = 0.6161,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6220'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/2b34764d-637c-48f5-aa70-31e15c965db6'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'adaptability to new environments; professional accountability',
    r.evidence_text = 'build a sense of strict compliance with regulations on intellectual property and professional ethics',
    r.final_score = 0.6098,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6220'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/cef5c0f8-1e40-4c09-b6a7-aa7811849e5d'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'ethical decision-making; problem decomposition',
    r.evidence_text = 'build a sense of strict compliance with regulations on intellectual property and professional ethics',
    r.final_score = 0.5979,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6220'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/9ce670ec-318c-4a91-9179-03437db728dc'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'project management; technical documentation literacy',
    r.evidence_text = 'Ability to research documentation, proficiency in planning, and application of acquired knowledge to deploy open-source software development solutions',
    r.final_score = 0.5822,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();

