// SUPPORTS_SKILL relations for SC6236
// Generated by supports_skill_pipeline M5
// Total relations: 5

MATCH (c:Course {course_id: 'SC6236'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/edebd83d-35f6-4ed5-a940-6c203d178c01'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'evidence-based decision making',
    r.evidence_text = 'The techniques and theories covered include: classification, clustering, association rules, etc',
    r.final_score = 0.6801,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6236'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/3ce1fe19-7f9e-4070-941d-651673a5693b'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'evidence-based decision making',
    r.evidence_text = 'The techniques and theories covered include: classification, clustering, association rules, etc',
    r.final_score = 0.6680,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6236'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/7b5cce4d-c7fe-4119-b48f-70aa05391787'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'abstract modeling; information synthesis',
    r.evidence_text = 'Course: Data Mining and Applications',
    r.final_score = 0.6405,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6236'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/98a1dec3-8138-4f46-a596-5e2a83b884b9'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'quantitative literacy; statistical intuition; systematic troubleshooting',
    r.evidence_text = 'CLO: Ability to use data mining algorithms for several basic problems Ability to apply data mining techniques and software tools to practical problems',
    r.final_score = 0.6391,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6236'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/5b26f08b-88bc-45f0-b901-530d7786466b'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'abstract modeling; critical thinking; technical adaptability',
    r.evidence_text = 'Description: The course provides learners with basic ideas and issues related to data prediction and description',
    r.final_score = 0.6347,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();

