// SUPPORTS_SKILL relations for SC6222_BS
// Generated by supports_skill_pipeline M5
// Total relations: 4

MATCH (c:Course {course_id: 'SC6222_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/6014921e-1d25-4039-adc2-04852d61880e'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'debugging and troubleshooting methodology; standardization adherence',
    r.evidence_text = 'Course: Tích hợp hệ thống phần mềm',
    r.final_score = 0.7856,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6222_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/96eb286a-58b7-45ff-a916-5578d0b79b8c'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'abstract modeling; debugging and troubleshooting methodology; technical adaptability',
    r.evidence_text = 'Enhance proactivity, personal responsibility, self-learning capability, and the ability to update new technologies to solve practical problems in modern software development',
    r.final_score = 0.7410,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6222_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/ed1d8bd4-cd2a-4c64-b665-56d70651026c'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'debugging and troubleshooting methodology; interface design principles; interoperability mindset',
    r.evidence_text = 'Objectives: Equip students with advanced concepts, methods, techniques, and technologies such as XML, XSD, XSLT, JSON, DOM, and Web APIs in software system integration',
    r.final_score = 0.7149,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6222_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/b105ec9b-0857-41d6-8d07-a83e58b73d90'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'debugging and troubleshooting methodology; systems thinking',
    r.evidence_text = 'Course: Tích hợp hệ thống phần mềm',
    r.final_score = 0.5931,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();

