// SUPPORTS_SKILL relations for SC6232
// Generated by supports_skill_pipeline M5
// Total relations: 6

MATCH (c:Course {course_id: 'SC6232'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/89f6560b-2194-45c9-9ece-d33049a73eef'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'cross-disciplinary synthesis; hardware-software integration',
    r.evidence_text = 'Course: Embedded Programming and IoT',
    r.final_score = 0.7057,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6232'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/ed1d8bd4-cd2a-4c64-b665-56d70651026c'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'iterative design process; resource-constrained optimization; troubleshooting methodology',
    r.evidence_text = 'CLO: Deploying embedded systems to solve practical problems',
    r.final_score = 0.6768,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6232'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/00c04e40-35ea-4ed1-824c-82f936c8f876'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'iterative design process; resource-constrained optimization; troubleshooting methodology',
    r.evidence_text = 'CLO: Deploying embedded systems to solve practical problems',
    r.final_score = 0.6243,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6232'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/925463a7-d51f-4d5b-9f79-4d28cf30acde'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'hardware-software integration; resource-constrained optimization',
    r.evidence_text = 'Course: Embedded Programming and IoT',
    r.final_score = 0.5639,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6232'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/85f46538-ae70-498a-bfbc-b8ddafe96c7d'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'hardware-software integration; iterative design process; risk assessment',
    r.evidence_text = 'Course: Embedded Programming and IoT',
    r.final_score = 0.5190,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6232'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/397da142-ab35-48fe-b154-7c38f447adfb'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'resource-constrained optimization; systems thinking',
    r.evidence_text = 'Deploying IoT systems to solve practical problems',
    r.final_score = 0.4971,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();

