// SUPPORTS_SKILL relations for SC6224
// Generated by supports_skill_pipeline M5
// Total relations: 6

MATCH (c:Course {course_id: 'SC6224'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/9b9de2a4-d8af-4a7b-933a-a8334ae60067'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'creative synthesis; visual communication',
    r.evidence_text = 'Apply knowledge to design practical website interfaces',
    r.final_score = 0.7916,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6224'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/8696aff0-18c0-4ba6-a4d0-9a21861b3e5e'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'creative synthesis; technical documentation literacy',
    r.evidence_text = 'Apply knowledge to design practical website interfaces',
    r.final_score = 0.5807,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6224'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/c2999f0c-eb37-4cdf-b9b0-82107b628794'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'creative synthesis; visual communication',
    r.evidence_text = 'Apply knowledge to design practical website interfaces',
    r.final_score = 0.5369,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6224'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/03ff0d53-573a-47a0-a0ad-1995815a4339'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'information architecture; visual communication',
    r.evidence_text = 'Apply knowledge to design practical website interfaces',
    r.final_score = 0.5170,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6224'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/69bbd53f-fbb0-4476-b4b2-ef7844464e28'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'debugging mindset',
    r.evidence_text = 'Apply knowledge to design practical website interfaces',
    r.final_score = 0.4943,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6224'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/8c88d336-c249-4537-b26e-d679a85c4b9b'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'creative synthesis; debugging mindset',
    r.evidence_text = 'Apply knowledge to design practical website interfaces',
    r.final_score = 0.4873,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();

