// SUPPORTS_SKILL relations for SC6202
// Generated by supports_skill_pipeline M5
// Total relations: 4

MATCH (c:Course {course_id: 'SC6202'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/98a1dec3-8138-4f46-a596-5e2a83b884b9'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'algorithmic mindset; quantitative reasoning',
    r.evidence_text = 'Course: Optimization',
    r.final_score = 0.8340,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6202'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/cdd8b6b2-2fd9-453c-8d62-8a1dc6efcd49'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'algorithmic mindset; systems thinking',
    r.evidence_text = 'Course: Optimization',
    r.final_score = 0.7702,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6202'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/8369c2d6-c100-4cf6-bd83-9668d8678433'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'critical evaluation of trade-offs; pattern recognition',
    r.evidence_text = 'Course: Optimization',
    r.final_score = 0.7699,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6202'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/8b0f73ff-d36b-4196-bb83-464c3a6ef07d'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'problem decomposition; quantitative reasoning; strategic planning',
    r.evidence_text = 'Proactively form ideas, design optimization models, and make decisions based on quantitative analysis, selecting solution methods, and evaluating results',
    r.final_score = 0.6863,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();

