// SUPPORTS_SKILL relations for SC6214
// Generated by supports_skill_pipeline M5
// Total relations: 7

MATCH (c:Course {course_id: 'SC6214'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/ed1d8bd4-cd2a-4c64-b665-56d70651026c'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'architectural design patterns; debugging and troubleshooting methodology; project planning',
    r.evidence_text = 'Program complex business logic, control input data validation, and handle exceptions effectively',
    r.final_score = 0.8039,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6214'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/96eb286a-58b7-45ff-a916-5578d0b79b8c'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'architectural design patterns; debugging and troubleshooting methodology; project planning',
    r.evidence_text = 'Program complex business logic, control input data validation, and handle exceptions effectively',
    r.final_score = 0.6900,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6214'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/21d2f96d-35f7-4e3f-9745-c533d2dd6e97'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'architectural design patterns; debugging and troubleshooting methodology',
    r.evidence_text = 'Program complex business logic, control input data validation, and handle exceptions effectively',
    r.final_score = 0.6601,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6214'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/83218cac-3599-417e-93d2-26013cdccd98'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'architectural design patterns; systems thinking',
    r.evidence_text = 'NET ecosystem to solve practical problems',
    r.final_score = 0.6496,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6214'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/8ff015a0-98ea-4d80-a23e-1f68110a919e'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'architectural design patterns; systems thinking',
    r.evidence_text = 'NET ecosystem to solve practical problems',
    r.final_score = 0.6439,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6214'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/56a7f561-1d55-43c9-9cd7-36a0a9bc6c50'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'architectural design patterns; debugging and troubleshooting methodology',
    r.evidence_text = 'Program complex business logic, control input data validation, and handle exceptions effectively',
    r.final_score = 0.6359,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6214'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/bec4359e-cb92-468f-a997-8fb28e32fba9'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'lifecycle management; project planning',
    r.evidence_text = 'Demonstrate a serious work attitude, strictly adhering to schedules and software development processes',
    r.final_score = 0.6108,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();

