// SUPPORTS_SKILL relations for SC6200
// Generated by supports_skill_pipeline M5
// Total relations: 6

MATCH (c:Course {course_id: 'SC6200'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/cef5c0f8-1e40-4c09-b6a7-aa7811849e5d'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'collaborative problem solving; complex system analysis; ethical decision-making',
    r.evidence_text = 'participate effectively in teamwork during the analysis, operation, and handling of cybersecurity incidents',
    r.final_score = 0.8052,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6200'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/3ff589b7-68df-4ea5-ae41-b395bdb2378f'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'ethical decision-making; regulatory compliance awareness; risk assessment mindset',
    r.evidence_text = 'Apply cybersecurity knowledge to implement protective measures for information systems, computing systems, and computer networks',
    r.final_score = 0.7358,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6200'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/0ffdb6ac-03b5-4f1c-bfcc-3d9cb874fdf9'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'ethical decision-making',
    r.evidence_text = 'CLO: Recognize and explain the fundamental principles of cybersecurity, the role of teamwork, and identify professional, legal, and ethical responsibilities in cybersecurity practice',
    r.final_score = 0.6860,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6200'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/397da142-ab35-48fe-b154-7c38f447adfb'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'complex system analysis; systems thinking',
    r.evidence_text = 'Analyze, evaluate, and propose comprehensive cybersecurity solutions for IT systems',
    r.final_score = 0.6569,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6200'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/4134622c-c3fb-4a41-beb6-6d58ba5107db'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'complex system analysis; professional accountability; regulatory compliance awareness',
    r.evidence_text = 'participate effectively in teamwork during the analysis, operation, and handling of cybersecurity incidents',
    r.final_score = 0.6567,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6200'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/426ceaba-6867-481c-bb6b-aee3933da7d2'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'risk assessment mindset; technical communication',
    r.evidence_text = 'coordinate teams, manage and safely operate computing systems/information systems to meet the requirements of users and organizations',
    r.final_score = 0.5994,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();

