// SUPPORTS_SKILL relations for SC6261
// Generated by supports_skill_pipeline M5
// Total relations: 2

MATCH (c:Course {course_id: 'SC6261'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/3e23db60-0c3d-498a-a6ac-ffbed0ecb033'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'accessibility advocacy',
    r.evidence_text = 'Objectives: Present fundamental issues regarding human-computer interaction',
    r.final_score = 0.7651,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6261'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/9ce670ec-318c-4a91-9179-03437db728dc'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'collaborative design; technical documentation',
    r.evidence_text = 'Thông qua học phần này, người học thiết kế được giao diện và tương tác giữa người dùng và máy tính',
    r.final_score = 0.5521,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();

