// SUPPORTS_SKILL relations for SC6211
// Generated by supports_skill_pipeline M5
// Total relations: 4

MATCH (c:Course {course_id: 'SC6211'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/ed1d8bd4-cd2a-4c64-b665-56d70651026c'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'debugging methodology; systems thinking',
    r.evidence_text = 'Identify and fix basic errors in the program',
    r.final_score = 0.8269,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6211'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/5be3d306-6cf1-4b49-aa1d-01651dd4ba4c'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'attention to detail; logical structuring; modular design mindset',
    r.evidence_text = 'Design or read class diagram designs and implement programs using an object-oriented approach',
    r.final_score = 0.7980,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6211'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/5b9cde20-f1b9-4adc-bfb3-dbf70b14138d'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'logical structuring; technical communication',
    r.evidence_text = '), object-oriented problem-solving approaches',
    r.final_score = 0.7219,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6211'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/21d2f96d-35f7-4e3f-9745-c533d2dd6e97'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'debugging methodology; logical structuring',
    r.evidence_text = 'Identify and fix basic errors in the program',
    r.final_score = 0.6207,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();

