// SUPPORTS_SKILL relations for SC6244
// Generated by supports_skill_pipeline M5
// Total relations: 9

MATCH (c:Course {course_id: 'SC6244'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/98a1dec3-8138-4f46-a596-5e2a83b884b9'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'iterative problem solving; quantitative analysis',
    r.evidence_text = 'applying, selecting, and experimenting with algorithms for specific problems',
    r.final_score = 0.8296,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6244'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/5608d5a0-6d5e-43b7-be37-616501729bb4'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'algorithmic thinking; iterative problem solving; quantitative analysis',
    r.evidence_text = 'applying, selecting, and experimenting with algorithms for specific problems',
    r.final_score = 0.8274,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6244'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/edebd83d-35f6-4ed5-a940-6c203d178c01'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'abstract modeling; quantitative analysis; self-directed learning',
    r.evidence_text = 'Objectives: The course equips students with knowledge of search strategies, knowledge representation, regression, basic machine learning, and neural networks',
    r.final_score = 0.7306,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6244'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/45f1ae17-c20d-40fc-9307-7d33b6ca9213'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'pattern recognition',
    r.evidence_text = 'Course: Artificial Intelligence',
    r.final_score = 0.7109,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6244'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/8369c2d6-c100-4cf6-bd83-9668d8678433'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'pattern recognition; technical documentation skills',
    r.evidence_text = 'Complete online lessons on the system',
    r.final_score = 0.6868,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6244'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/68ef0e4d-5542-4e64-84f4-752cce5a3c22'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'abstract modeling; critical evaluation of trade-offs',
    r.evidence_text = 'Upon completion, students are capable of applying certain AI models in practice',
    r.final_score = 0.6710,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6244'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/5b26f08b-88bc-45f0-b901-530d7786466b'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'algorithmic thinking; quantitative analysis; technical documentation skills',
    r.evidence_text = 'applying, selecting, and experimenting with algorithms for specific problems',
    r.final_score = 0.6696,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6244'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/7b5cce4d-c7fe-4119-b48f-70aa05391787'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'abstract modeling; systematic experimentation',
    r.evidence_text = 'Select and experiment with appropriate solutions for practical problems',
    r.final_score = 0.6354,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6244'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/7b0d5000-00da-4864-b776-6de49a87a669'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'algorithmic thinking; technical documentation skills',
    r.evidence_text = 'applying, selecting, and experimenting with algorithms for specific problems',
    r.final_score = 0.6223,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();

