// SUPPORTS_SKILL relations for SC6223
// Generated by supports_skill_pipeline M5
// Total relations: 5

MATCH (c:Course {course_id: 'SC6223'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/8b0f73ff-d36b-4196-bb83-464c3a6ef07d'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'formal reasoning; mathematical maturity; pattern recognition',
    r.evidence_text = 'Course: Discrete Mathematics',
    r.final_score = 0.8260,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6223'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/7b5cce4d-c7fe-4119-b48f-70aa05391787'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'formal reasoning; systematic analysis',
    r.evidence_text = 'Course: Discrete Mathematics',
    r.final_score = 0.7178,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6223'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/5b26f08b-88bc-45f0-b901-530d7786466b'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'formal reasoning; precision in communication',
    r.evidence_text = 'Course: Discrete Mathematics',
    r.final_score = 0.6862,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6223'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/33e584f9-ff7a-4979-bfc0-5a3a374a145a'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'pattern recognition; systematic analysis',
    r.evidence_text = 'Apply algorithms to a number of practical problems',
    r.final_score = 0.5991,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6223'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/89f6560b-2194-45c9-9ece-d33049a73eef'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'algorithmic thinking; pattern recognition',
    r.evidence_text = 'Apply algorithms to a number of practical problems',
    r.final_score = 0.5794,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();

