// SUPPORTS_SKILL relations for SC6213
// Generated by supports_skill_pipeline M5
// Total relations: 6

MATCH (c:Course {course_id: 'SC6213'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/af7ae54f-4649-4c16-87c7-59ba41d4d57f'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'critical evaluation of technology stacks; software lifecycle awareness',
    r.evidence_text = 'Implement software according to design and meet practical requirements',
    r.final_score = 0.7453,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6213'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/9ce670ec-318c-4a91-9179-03437db728dc'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'critical evaluation of technology stacks; software lifecycle awareness',
    r.evidence_text = 'Implement software according to design and meet practical requirements',
    r.final_score = 0.6357,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6213'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/6b6a9252-2ed7-4862-a02f-1578f4a532ea'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'collaborative project management; critical evaluation of technology stacks',
    r.evidence_text = 'Implement software according to design and meet practical requirements',
    r.final_score = 0.6054,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6213'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/89f6560b-2194-45c9-9ece-d33049a73eef'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'critical evaluation of technology stacks; system design mindset',
    r.evidence_text = 'Implement software according to design and meet practical requirements',
    r.final_score = 0.6006,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6213'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/013441c1-1f13-47e9-80c4-9a53e8e1bc05'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'critical evaluation of technology stacks; debugging and troubleshooting methodology; software lifecycle awareness',
    r.evidence_text = 'Implement software according to design and meet practical requirements',
    r.final_score = 0.5880,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6213'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/24c200e5-be20-4370-a137-ab53797f3a17'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'critical evaluation of technology stacks; software lifecycle awareness; system design mindset',
    r.evidence_text = 'Implement software according to design and meet practical requirements',
    r.final_score = 0.5754,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();

