// SUPPORTS_SKILL relations for SC6260
// Generated by supports_skill_pipeline M5
// Total relations: 6

MATCH (c:Course {course_id: 'SC6260'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/bec4359e-cb92-468f-a997-8fb28e32fba9'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'problem decomposition; project management',
    r.evidence_text = 'Description: The specialized project aims to apply acquired information technology specialized knowledge to solve a small practical problem',
    r.final_score = 0.7584,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6260'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/4134622c-c3fb-4a41-beb6-6d58ba5107db'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'professional ethics',
    r.evidence_text = 'Course: Major Project (Information Technology)',
    r.final_score = 0.5003,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6260'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/ec6df9cb-be92-4027-80fa-83b70aabce58'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'resourcefulness; technical documentation',
    r.evidence_text = 'Use supporting tools to design, deploy, and test the system',
    r.final_score = 0.4856,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6260'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/89f6560b-2194-45c9-9ece-d33049a73eef'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'professional communication; professional ethics',
    r.evidence_text = 'Course: Major Project (Information Technology)',
    r.final_score = 0.4789,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6260'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/9ce670ec-318c-4a91-9179-03437db728dc'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'stakeholder management; technical documentation',
    r.evidence_text = 'Use supporting tools to design, deploy, and test the system',
    r.final_score = 0.4777,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6260'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/33d49d4f-31ec-473f-9b8a-b555aa5116bb'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'iterative refinement',
    r.evidence_text = 'Description: The specialized project aims to apply acquired information technology specialized knowledge to solve a small practical problem',
    r.final_score = 0.3326,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();

