// SUPPORTS_SKILL relations for SC6206
// Generated by supports_skill_pipeline M5
// Total relations: 5

MATCH (c:Course {course_id: 'SC6206'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/2450c3b3-e78e-435b-b84d-e05d984e71dc'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'data modeling mindset; information architecture',
    r.evidence_text = 'Develop students\' capability to proactively analyze data requirements, propose and execute basic database designs',
    r.final_score = 0.8423,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6206'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/edebd83d-35f6-4ed5-a940-6c203d178c01'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'collaborative problem solving; data modeling mindset',
    r.evidence_text = 'Develop students\' capability to proactively analyze data requirements, propose and execute basic database designs',
    r.final_score = 0.7997,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6206'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/fecf8a0d-62c4-4e71-9b03-0f4fc2ad7bf5'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'collaborative problem solving; data modeling mindset',
    r.evidence_text = 'Develop students\' capability to proactively analyze data requirements, propose and execute basic database designs',
    r.final_score = 0.7503,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6206'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/c453cf81-6197-428e-84c6-70c773b63f27'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'information architecture',
    r.evidence_text = 'Course: Database',
    r.final_score = 0.6817,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6206'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/43ae58b9-5e56-4524-b45a-b422777a0576'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'abstract thinking; attention to detail',
    r.evidence_text = 'foster responsibility in studying, individual and teamwork, as well as in data usage and management',
    r.final_score = 0.6542,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();

