// SUPPORTS_SKILL relations for SC6267
// Generated by supports_skill_pipeline M5
// Total relations: 8

MATCH (c:Course {course_id: 'SC6267'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/e9575f7f-053a-439e-8074-f93df3334e92'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'professional ethics; technical documentation standards',
    r.evidence_text = 'Evaluate the developed software solution based on technical criteria, performance, and requirement compliance, thereby proposing improvements to enhance the quality and feasibility of the information system',
    r.final_score = 0.8275,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6267'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/327d15c8-29ff-4ad4-a4fe-6536d777a45f'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'technical documentation standards',
    r.evidence_text = 'Evaluate the developed software solution based on technical criteria, performance, and requirement compliance, thereby proposing improvements to enhance the quality and feasibility of the information system',
    r.final_score = 0.7930,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6267'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/9ce670ec-318c-4a91-9179-03437db728dc'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'technical documentation standards',
    r.evidence_text = 'Evaluate the developed software solution based on technical criteria, performance, and requirement compliance, thereby proposing improvements to enhance the quality and feasibility of the information system',
    r.final_score = 0.6847,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6267'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/ccdbd9bb-4faf-403c-a968-e8bf487f8a53'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'professional communication; resource allocation; technical documentation standards',
    r.evidence_text = 'Evaluate the developed software solution based on technical criteria, performance, and requirement compliance, thereby proposing improvements to enhance the quality and feasibility of the information system',
    r.final_score = 0.6021,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6267'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/9d2e926f-53d9-41f5-98f3-19dfaa687f3f'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'technical documentation standards; time management',
    r.evidence_text = 'Evaluate the developed software solution based on technical criteria, performance, and requirement compliance, thereby proposing improvements to enhance the quality and feasibility of the information system',
    r.final_score = 0.5973,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6267'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/7111b95d-0ce3-441a-9d92-4c75d05c4388'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'decision-making under uncertainty; stakeholder management; time management',
    r.evidence_text = 'Formulate the capacity for self-study, independent research, systems thinking, and innovation',
    r.final_score = 0.5792,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6267'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/94dd823c-148e-4614-a6e8-99249b16357d'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'decision-making under uncertainty; stakeholder management; time management',
    r.evidence_text = 'Formulate the capacity for self-study, independent research, systems thinking, and innovation',
    r.final_score = 0.5695,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6267'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/cef5c0f8-1e40-4c09-b6a7-aa7811849e5d'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'professional ethics',
    r.evidence_text = 'enhance personal and team responsibility during the execution of specialized projects, preparing for internships and graduation theses',
    r.final_score = 0.5506,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();

