// SUPPORTS_SKILL relations for SC6268
// Generated by supports_skill_pipeline M5
// Total relations: 7

MATCH (c:Course {course_id: 'SC6268'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/7111b95d-0ce3-441a-9d92-4c75d05c4388'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'cross-functional collaboration; project lifecycle awareness',
    r.evidence_text = 'Demonstrate the ability to work independently or in a team to conceptualize the design of industry-standard business documentation (BRD, SRS)',
    r.final_score = 0.8219,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6268'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/327d15c8-29ff-4ad4-a4fe-6536d777a45f'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'professional documentation standards; stakeholder management',
    r.evidence_text = 'Demonstrate the ability to work independently or in a team to conceptualize the design of industry-standard business documentation (BRD, SRS)',
    r.final_score = 0.8176,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6268'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/cdd8b6b2-2fd9-453c-8d62-8a1dc6efcd49'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'project lifecycle awareness; systems thinking',
    r.evidence_text = 'have the ability to plan analysis',
    r.final_score = 0.7752,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6268'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/7159e587-c7cb-4ec0-a662-03e1dee2cccb'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'stakeholder management; technical writing',
    r.evidence_text = 'CLO: Demonstrate basic knowledge of business analysis such as the BACCM framework, needs, requirements, and risks from stakeholders',
    r.final_score = 0.6019,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6268'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/bd698bbe-7003-4508-b422-46c2ff4d5e95'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'stakeholder management; systems thinking',
    r.evidence_text = 'have the ability to plan analysis',
    r.final_score = 0.5996,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6268'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/bec4359e-cb92-468f-a997-8fb28e32fba9'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'ethical decision-making; project lifecycle awareness; stakeholder management',
    r.evidence_text = 'CLO: Demonstrate basic knowledge of business analysis such as the BACCM framework, needs, requirements, and risks from stakeholders',
    r.final_score = 0.5753,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6268'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/09f2f811-a3fb-4de3-a70f-6420a6935575'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'project lifecycle awareness; stakeholder management; systems thinking',
    r.evidence_text = 'have the ability to plan analysis',
    r.final_score = 0.5564,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();

