// SUPPORTS_SKILL relations for SC6262
// Generated by supports_skill_pipeline M5
// Total relations: 7

MATCH (c:Course {course_id: 'SC6262'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/7111b95d-0ce3-441a-9d92-4c75d05c4388'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'adaptability to new technologies; technical project management',
    r.evidence_text = 'Take personal responsibility for progress, product quality, and proactively resolve complex technical issues during development',
    r.final_score = 0.7735,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6262'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/94dd823c-148e-4614-a6e8-99249b16357d'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'adaptability to new technologies; technical project management',
    r.evidence_text = 'Take personal responsibility for progress, product quality, and proactively resolve complex technical issues during development',
    r.final_score = 0.6675,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6262'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/24c200e5-be20-4370-a137-ab53797f3a17'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'adaptability to new technologies; collaborative workflow; system design',
    r.evidence_text = 'Demonstrate the ability to work independently and effectively in a team',
    r.final_score = 0.6312,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6262'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/ed1d8bd4-cd2a-4c64-b665-56d70651026c'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'collaborative workflow; system design; troubleshooting methodology',
    r.evidence_text = 'Utilize various PHP frameworks in solving practical problems',
    r.final_score = 0.6242,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6262'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/8ff015a0-98ea-4d80-a23e-1f68110a919e'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'adaptability to new technologies; system design',
    r.evidence_text = 'Proficiently apply OOP principles and the MVC pattern to analyze, design, and develop applications',
    r.final_score = 0.5944,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6262'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/9ce670ec-318c-4a91-9179-03437db728dc'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'collaborative workflow; technical project management',
    r.evidence_text = 'Take personal responsibility for progress, product quality, and proactively resolve complex technical issues during development',
    r.final_score = 0.5917,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6262'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/3ff589b7-68df-4ea5-ae41-b395bdb2378f'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'quality assurance mindset; risk assessment',
    r.evidence_text = 'Take personal responsibility for progress, product quality, and proactively resolve complex technical issues during development',
    r.final_score = 0.5711,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();

