// SUPPORTS_SKILL relations for SC6221
// Generated by supports_skill_pipeline M5
// Total relations: 4

MATCH (c:Course {course_id: 'SC6221'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/e464363b-8346-421d-9035-52118b76d8c8'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'computational thinking; critical evaluation of precision',
    r.evidence_text = 'Course: Numerical Methods for Programming',
    r.final_score = 0.8532,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6221'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/21d2f96d-35f7-4e3f-9745-c533d2dd6e97'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'abstract problem solving; computational thinking; critical evaluation of precision',
    r.evidence_text = 'Apply numerical methods to solve practical problems',
    r.final_score = 0.7515,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6221'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/5b26f08b-88bc-45f0-b901-530d7786466b'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'computational thinking; problem decomposition; technical documentation skills',
    r.evidence_text = 'Course: Numerical Methods for Programming',
    r.final_score = 0.7451,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6221'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/7b5cce4d-c7fe-4119-b48f-70aa05391787'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'computational thinking; problem decomposition',
    r.evidence_text = 'Course: Numerical Methods for Programming',
    r.final_score = 0.6148,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();

