// SUPPORTS_SKILL relations for SC6219
// Generated by supports_skill_pipeline M5
// Total relations: 3

MATCH (c:Course {course_id: 'SC6219'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/ed1d8bd4-cd2a-4c64-b665-56d70651026c'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'complex problem decomposition; debugging and troubleshooting methodology; iterative development process',
    r.evidence_text = 'Course: Mobile application development',
    r.final_score = 0.7963,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6219'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/c4b626c1-e71c-44ec-9f88-042766f37fcc'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'adaptability to evolving technology stacks; usability evaluation',
    r.evidence_text = 'Apply a systems approach to deploy software solutions on the Android platform ensuring user goals, compliance with laws, and professional ethics',
    r.final_score = 0.6738,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6219'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/2450c3b3-e78e-435b-b84d-e05d984e71dc'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'system architecture awareness',
    r.evidence_text = 'Apply a systems approach to deploy software solutions on the Android platform ensuring user goals, compliance with laws, and professional ethics',
    r.final_score = 0.5605,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();

