// SUPPORTS_SKILL relations for SC6212
// Generated by supports_skill_pipeline M5
// Total relations: 4

MATCH (c:Course {course_id: 'SC6212'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/5be3d306-6cf1-4b49-aa1d-01651dd4ba4c'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'abstract modeling; debugging and troubleshooting methodology',
    r.evidence_text = 'Apply Java programming techniques to solve specific problems',
    r.final_score = 0.8035,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6212'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/21d2f96d-35f7-4e3f-9745-c533d2dd6e97'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'computational logic; systematic problem decomposition',
    r.evidence_text = 'Forms a serious, proactive learning attitude and logical thinking during the programming learning process',
    r.final_score = 0.7615,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6212'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/5b9cde20-f1b9-4adc-bfb3-dbf70b14138d'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'computational logic; persistence in problem-solving; systematic problem decomposition',
    r.evidence_text = 'Forms a serious, proactive learning attitude and logical thinking during the programming learning process',
    r.final_score = 0.7166,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6212'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/19a8293b-8e95-4de3-983f-77484079c389'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'computational logic; debugging and troubleshooting methodology',
    r.evidence_text = 'Apply Java programming techniques to solve specific problems',
    r.final_score = 0.6817,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();

