// SUPPORTS_SKILL relations for SC6266
// Generated by supports_skill_pipeline M5
// Total relations: 5

MATCH (c:Course {course_id: 'SC6266'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/ed1d8bd4-cd2a-4c64-b665-56d70651026c'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'debugging and troubleshooting methodology; system architecture design; user interface design principles',
    r.evidence_text = 'Apply the software development process to solve practical problems using Python',
    r.final_score = 0.7652,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6266'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/2450c3b3-e78e-435b-b84d-e05d984e71dc'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'system architecture design; user interface design principles',
    r.evidence_text = 'After completing this course, learners will be able to build GUI applications to display and interact with database systems',
    r.final_score = 0.6490,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6266'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/21d2f96d-35f7-4e3f-9745-c533d2dd6e97'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'integration of disparate technologies; system architecture design; user interface design principles',
    r.evidence_text = 'After completing this course, learners will be able to build GUI applications to display and interact with database systems',
    r.final_score = 0.6176,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6266'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/09f2f811-a3fb-4de3-a70f-6420a6935575'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'software lifecycle management',
    r.evidence_text = 'Apply the software development process to solve practical problems using Python',
    r.final_score = 0.5764,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6266'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/925463a7-d51f-4d5b-9f79-4d28cf30acde'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'integration of disparate technologies; software lifecycle management; user interface design principles',
    r.evidence_text = 'Apply the software development process to solve practical problems using Python',
    r.final_score = 0.5734,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();

