// SUPPORTS_SKILL relations for SC6205
// Generated by supports_skill_pipeline M5
// Total relations: 8

MATCH (c:Course {course_id: 'SC6205'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/e464363b-8346-421d-9035-52118b76d8c8'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'computational thinking; self-directed learning',
    r.evidence_text = 'Proactively learn and acquire knowledge, demonstrating self-study awareness and a serious attitude toward learning',
    r.final_score = 0.8642,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6205'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/7b5cce4d-c7fe-4119-b48f-70aa05391787'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'computational thinking',
    r.evidence_text = 'Course: Data Structures and Algorithms',
    r.final_score = 0.7230,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6205'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/45f1ae17-c20d-40fc-9307-7d33b6ca9213'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'pattern recognition',
    r.evidence_text = '), algorithms (sorting, searching, etc',
    r.final_score = 0.7074,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6205'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/edebd83d-35f6-4ed5-a940-6c203d178c01'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'attention to detail; self-directed learning; systematic debugging',
    r.evidence_text = 'Proactively learn and acquire knowledge, demonstrating self-study awareness and a serious attitude toward learning',
    r.final_score = 0.7065,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6205'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/ecc4552a-92c5-4222-b18d-faf5ac841080'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'abstract modeling; pattern recognition; self-directed learning',
    r.evidence_text = 'Proactively learn and acquire knowledge, demonstrating self-study awareness and a serious attitude toward learning',
    r.final_score = 0.7001,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6205'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/5be3d306-6cf1-4b49-aa1d-01651dd4ba4c'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'abstract modeling',
    r.evidence_text = 'Course: Data Structures and Algorithms',
    r.final_score = 0.6683,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6205'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/8b0f73ff-d36b-4196-bb83-464c3a6ef07d'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'critical evaluation; logical reasoning; mathematical maturity',
    r.evidence_text = 'the ability to select and apply appropriate data structures and algorithms to specific problems',
    r.final_score = 0.6054,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6205'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/2450c3b3-e78e-435b-b84d-e05d984e71dc'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'abstract modeling',
    r.evidence_text = 'Course: Data Structures and Algorithms',
    r.final_score = 0.6042,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();

