// SUPPORTS_SKILL relations for SC6215
// Generated by supports_skill_pipeline M5
// Total relations: 3

MATCH (c:Course {course_id: 'SC6215'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/ed1d8bd4-cd2a-4c64-b665-56d70651026c'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'debugging and troubleshooting methodology; project lifecycle management; user-centric design perspective',
    r.evidence_text = 'Proactively propose ideas, design interfaces, and functional structures of websites',
    r.final_score = 0.6722,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6215'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/21d2f96d-35f7-4e3f-9745-c533d2dd6e97'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'debugging and troubleshooting methodology; user-centric design perspective',
    r.evidence_text = 'Proactively propose ideas, design interfaces, and functional structures of websites',
    r.final_score = 0.6365,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6215'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/09f2f811-a3fb-4de3-a70f-6420a6935575'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'collaborative workflow management; project lifecycle management; user-centric design perspective',
    r.evidence_text = 'Proactively propose ideas, design interfaces, and functional structures of websites',
    r.final_score = 0.6207,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();

