// SUPPORTS_SKILL relations for SC6265
// Generated by supports_skill_pipeline M5
// Total relations: 8

MATCH (c:Course {course_id: 'SC6265'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/6014921e-1d25-4039-adc2-04852d61880e'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'structured workflow management; systematic debugging',
    r.evidence_text = 'Proficient manipulation of file processing, data input/output, Object-Oriented Programming',
    r.final_score = 0.8018,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6265'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/5b9cde20-f1b9-4adc-bfb3-dbf70b14138d'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'algorithmic problem solving; resilience in troubleshooting; structured workflow management',
    r.evidence_text = 'Proficient manipulation of file processing, data input/output, Object-Oriented Programming',
    r.final_score = 0.6965,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6265'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/21d2f96d-35f7-4e3f-9745-c533d2dd6e97'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'algorithmic problem solving; computational thinking',
    r.evidence_text = 'Through this course, learners approach and solve problems naturally according to their inherent nature and implement them using the Python language, while also being introduced to basic programming techniques and applying them to solve specific problems',
    r.final_score = 0.6950,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6265'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/ed1d8bd4-cd2a-4c64-b665-56d70651026c'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'structured workflow management; systematic debugging',
    r.evidence_text = 'Proficient manipulation of file processing, data input/output, Object-Oriented Programming',
    r.final_score = 0.6053,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6265'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/5be3d306-6cf1-4b49-aa1d-01651dd4ba4c'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'abstract thinking; structured workflow management',
    r.evidence_text = 'Proficient manipulation of file processing, data input/output, Object-Oriented Programming',
    r.final_score = 0.5962,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6265'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/013441c1-1f13-47e9-80c4-9a53e8e1bc05'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'structured workflow management; systematic debugging',
    r.evidence_text = 'Proficient manipulation of file processing, data input/output, Object-Oriented Programming',
    r.final_score = 0.5900,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6265'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/925463a7-d51f-4d5b-9f79-4d28cf30acde'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'structured workflow management; systematic debugging',
    r.evidence_text = 'Proficient manipulation of file processing, data input/output, Object-Oriented Programming',
    r.final_score = 0.5780,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6265'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/7b5cce4d-c7fe-4119-b48f-70aa05391787'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'computational thinking; structured workflow management',
    r.evidence_text = 'Proficient manipulation of file processing, data input/output, Object-Oriented Programming',
    r.final_score = 0.5410,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();

