// SUPPORTS_SKILL relations for SC6229
// Generated by supports_skill_pipeline M5
// Total relations: 5

MATCH (c:Course {course_id: 'SC6229'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/7111b95d-0ce3-441a-9d92-4c75d05c4388'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'data-driven decision making; project lifecycle management',
    r.evidence_text = 'Be able to analyze management needs and utilize the basic functions of enterprise resource planning systems',
    r.final_score = 0.8225,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6229'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/bec4359e-cb92-468f-a997-8fb28e32fba9'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'operational efficiency mindset; project lifecycle management',
    r.evidence_text = 'Objectives: Understand the concept, role, structure, and operating principles of enterprise resource planning systems in businesses',
    r.final_score = 0.7785,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6229'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/3ce1fe19-7f9e-4070-941d-651673a5693b'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'data-driven decision making',
    r.evidence_text = 'Be able to analyze management needs and utilize the basic functions of enterprise resource planning systems',
    r.final_score = 0.7383,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6229'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/ccdbd9bb-4faf-403c-a968-e8bf487f8a53'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'business process mapping; systems thinking',
    r.evidence_text = 'Be able to analyze management needs and utilize the basic functions of enterprise resource planning systems',
    r.final_score = 0.7285,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6229'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/09f2f811-a3fb-4de3-a70f-6420a6935575'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'change management awareness; data-driven decision making; project lifecycle management',
    r.evidence_text = 'Be proactive in learning, work independently or in teams, and take responsibility for the outcomes of using enterprise resource planning systems',
    r.final_score = 0.5871,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();

