// SUPPORTS_SKILL relations for SC6208_BS
// Generated by supports_skill_pipeline M5
// Total relations: 3

MATCH (c:Course {course_id: 'SC6208_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/5b26f08b-88bc-45f0-b901-530d7786466b'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'algorithmic mindset; computational thinking; technical documentation literacy',
    r.evidence_text = 'Enhances logical thinking, attention to detail, self-learning capability, and a sense of responsibility in applying programming techniques to solve real-world problems',
    r.final_score = 0.8549,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6208_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/7b5cce4d-c7fe-4119-b48f-70aa05391787'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'algorithmic mindset; computational thinking',
    r.evidence_text = 'Enhances logical thinking, attention to detail, self-learning capability, and a sense of responsibility in applying programming techniques to solve real-world problems',
    r.final_score = 0.7895,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6208_BS'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/89f6560b-2194-45c9-9ece-d33049a73eef'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'logical reasoning; self-directed learning',
    r.evidence_text = 'Enhances logical thinking, attention to detail, self-learning capability, and a sense of responsibility in applying programming techniques to solve real-world problems',
    r.final_score = 0.5998,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();

