// SUPPORTS_SKILL relations for SC6263
// Generated by supports_skill_pipeline M5
// Total relations: 7

MATCH (c:Course {course_id: 'SC6263'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/93e65de1-923c-437e-aa5b-e6002967ce71'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'collaborative workflow management',
    r.evidence_text = 'Ready to collaborate in teamwork when solving practical problems',
    r.final_score = 0.8672,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6263'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/33d49d4f-31ec-473f-9b8a-b555aa5116bb'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'adaptability to evolving technologies; iterative problem solving',
    r.evidence_text = 'Ready to collaborate in teamwork when solving practical problems',
    r.final_score = 0.7508,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6263'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/8696aff0-18c0-4ba6-a4d0-9a21861b3e5e'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'collaborative workflow management; professional responsibility; technical documentation literacy',
    r.evidence_text = 'Ready to collaborate in teamwork when solving practical problems',
    r.final_score = 0.6111,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6263'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/8c88d336-c249-4537-b26e-d679a85c4b9b'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'collaborative workflow management',
    r.evidence_text = 'Ready to collaborate in teamwork when solving practical problems',
    r.final_score = 0.6097,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6263'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/123cf7c5-6a3b-419d-be4f-49a6cc020f9f'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'collaborative workflow management; cross-functional communication',
    r.evidence_text = 'Ready to collaborate in teamwork when solving practical problems',
    r.final_score = 0.6055,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6263'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/9b9de2a4-d8af-4a7b-933a-a8334ae60067'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'collaborative workflow management; information synthesis',
    r.evidence_text = 'Ready to collaborate in teamwork when solving practical problems',
    r.final_score = 0.5889,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6263'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/ed1d8bd4-cd2a-4c64-b665-56d70651026c'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'project management mindset; user-centric design thinking',
    r.evidence_text = 'Course: Advanced Web Design',
    r.final_score = 0.5858,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();

