// SUPPORTS_SKILL relations for SC6210
// Generated by supports_skill_pipeline M5
// Total relations: 7

MATCH (c:Course {course_id: 'SC6210'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/6014921e-1d25-4039-adc2-04852d61880e'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'collaborative version control workflows; debugging and troubleshooting methodology',
    r.evidence_text = 'Implement a software solution meeting given requirements using computer science tools and techniques',
    r.final_score = 0.8400,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6210'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/96eb286a-58b7-45ff-a916-5578d0b79b8c'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'adaptability to complex frameworks; collaborative version control workflows; debugging and troubleshooting methodology',
    r.evidence_text = 'Implement a software solution meeting given requirements using computer science tools and techniques',
    r.final_score = 0.7045,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6210'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/c453cf81-6197-428e-84c6-70c773b63f27'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'adaptability to complex frameworks; collaborative version control workflows; system architecture design',
    r.evidence_text = 'Implement a software solution meeting given requirements using computer science tools and techniques',
    r.final_score = 0.6973,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6210'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/24c200e5-be20-4370-a137-ab53797f3a17'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'adaptability to complex frameworks; collaborative version control workflows',
    r.evidence_text = 'Implement a software solution meeting given requirements using computer science tools and techniques',
    r.final_score = 0.6842,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6210'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/2450c3b3-e78e-435b-b84d-e05d984e71dc'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'collaborative version control workflows; system architecture design',
    r.evidence_text = 'Implement a software solution meeting given requirements using computer science tools and techniques',
    r.final_score = 0.6331,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6210'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/ed1d8bd4-cd2a-4c64-b665-56d70651026c'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'collaborative version control workflows; debugging and troubleshooting methodology',
    r.evidence_text = 'Implement a software solution meeting given requirements using computer science tools and techniques',
    r.final_score = 0.6317,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6210'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/09f2f811-a3fb-4de3-a70f-6420a6935575'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'collaborative version control workflows; software lifecycle management',
    r.evidence_text = 'Implement a software solution meeting given requirements using computer science tools and techniques',
    r.final_score = 0.6106,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();

