// SUPPORTS_SKILL relations for SC6241
// Generated by supports_skill_pipeline M5
// Total relations: 7

MATCH (c:Course {course_id: 'SC6241'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/85f46538-ae70-498a-bfbc-b8ddafe96c7d'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'problem decomposition; quality assurance mindset',
    r.evidence_text = 'evaluate teamwork effectiveness in complying with quality processes',
    r.final_score = 0.8389,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6241'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/24c200e5-be20-4370-a137-ab53797f3a17'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'adaptability to new technologies; professional collaboration; systems thinking',
    r.evidence_text = 'evaluate teamwork effectiveness in complying with quality processes',
    r.final_score = 0.7530,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6241'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/8ff015a0-98ea-4d80-a23e-1f68110a919e'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'structured documentation; systems thinking',
    r.evidence_text = 'The course helps students develop skills in requirements analysis, test case design and execution, and systematic bug tracking and management',
    r.final_score = 0.6664,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6241'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/fb7aee4d-f6c6-4a87-8e9d-8e542b3771f8'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'risk assessment; systems thinking',
    r.evidence_text = 'Apply testing techniques to practical problems',
    r.final_score = 0.6299,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6241'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/9ce670ec-318c-4a91-9179-03437db728dc'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'professional collaboration; technical communication',
    r.evidence_text = 'evaluate teamwork effectiveness in complying with quality processes',
    r.final_score = 0.6107,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6241'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/c4b626c1-e71c-44ec-9f88-042766f37fcc'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'adaptability to new technologies; process orientation',
    r.evidence_text = 'Students understand the role of testing in modern software development models such as Agile, DevOps, and CI/CD',
    r.final_score = 0.6087,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6241'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/9d2e926f-53d9-41f5-98f3-19dfaa687f3f'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'process orientation; professional collaboration',
    r.evidence_text = 'evaluate teamwork effectiveness in complying with quality processes',
    r.final_score = 0.5830,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();

