// SUPPORTS_SKILL relations for SC6240
// Generated by supports_skill_pipeline M5
// Total relations: 6

MATCH (c:Course {course_id: 'SC6240'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/3ff589b7-68df-4ea5-ae41-b395bdb2378f'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'infrastructure lifecycle management; regulatory compliance awareness; risk assessment',
    r.evidence_text = 'Demonstrate professional responsibility and ethics in deploying, designing, and administering basic network systems in compliance with legal principles',
    r.final_score = 0.8066,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6240'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/cdd8b6b2-2fd9-453c-8d62-8a1dc6efcd49'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'infrastructure lifecycle management; systems thinking',
    r.evidence_text = 'Network devices, network system design processes',
    r.final_score = 0.7217,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6240'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/0ffdb6ac-03b5-4f1c-bfcc-3d9cb874fdf9'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'ethical decision-making; troubleshooting methodology',
    r.evidence_text = 'Demonstrate professional responsibility and ethics in deploying, designing, and administering basic network systems in compliance with legal principles',
    r.final_score = 0.6746,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6240'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/397da142-ab35-48fe-b154-7c38f447adfb'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'infrastructure lifecycle management; systems thinking',
    r.evidence_text = 'Network devices, network system design processes',
    r.final_score = 0.6474,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6240'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/7f2afce6-e98b-4bbe-8441-d52b45e28ab8'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'infrastructure lifecycle management; regulatory compliance awareness',
    r.evidence_text = 'Demonstrate professional responsibility and ethics in deploying, designing, and administering basic network systems in compliance with legal principles',
    r.final_score = 0.6118,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6240'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/09f2f811-a3fb-4de3-a70f-6420a6935575'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'infrastructure lifecycle management',
    r.evidence_text = 'Network devices, network system design processes',
    r.final_score = 0.5783,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();

