// SUPPORTS_SKILL relations for SC6239
// Generated by supports_skill_pipeline M5
// Total relations: 7

MATCH (c:Course {course_id: 'SC6239'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/8ff015a0-98ea-4d80-a23e-1f68110a919e'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'critical evaluation of methodologies',
    r.evidence_text = 'as well as analyze requirements and propose software solutions to meet user objectives in practical problems',
    r.final_score = 0.8388,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6239'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/7111b95d-0ce3-441a-9d92-4c75d05c4388'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'critical evaluation of methodologies; project lifecycle management',
    r.evidence_text = 'Select and apply a suitable process model for a software project that meets user objectives',
    r.final_score = 0.8370,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6239'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/bec4359e-cb92-468f-a997-8fb28e32fba9'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'critical evaluation of methodologies; project lifecycle management',
    r.evidence_text = 'Select and apply a suitable process model for a software project that meets user objectives',
    r.final_score = 0.7900,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6239'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/9ce670ec-318c-4a91-9179-03437db728dc'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'stakeholder expectation management; technical documentation standards',
    r.evidence_text = 'software requirement specification documents',
    r.final_score = 0.7328,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6239'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/94dd823c-148e-4614-a6e8-99249b16357d'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'critical evaluation of methodologies; project lifecycle management',
    r.evidence_text = 'Select and apply a suitable process model for a software project that meets user objectives',
    r.final_score = 0.6735,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6239'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/fb7aee4d-f6c6-4a87-8e9d-8e542b3771f8'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'critical evaluation of methodologies; technical documentation standards',
    r.evidence_text = 'software requirement specification documents',
    r.final_score = 0.6697,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6239'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/09f2f811-a3fb-4de3-a70f-6420a6935575'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'critical evaluation of methodologies; project lifecycle management',
    r.evidence_text = 'Select and apply a suitable process model for a software project that meets user objectives',
    r.final_score = 0.6439,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();

