// SUPPORTS_SKILL relations for SC6234
// Generated by supports_skill_pipeline M5
// Total relations: 9

MATCH (c:Course {course_id: 'SC6234'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/2ddb1226-1117-4eb4-ae65-3a2f5a5a3c80'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'incident response planning; risk assessment mindset',
    r.evidence_text = 'Upon completion of the course, students are able to apply the acquired knowledge to deploy and handle situations to ensure system security and safety in accordance with legal principles and professional ethics',
    r.final_score = 0.8048,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6234'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/3ff589b7-68df-4ea5-ae41-b395bdb2378f'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'continuous monitoring mindset; professional accountability; risk assessment mindset',
    r.evidence_text = 'Upon completion of the course, students are able to apply the acquired knowledge to deploy and handle situations to ensure system security and safety in accordance with legal principles and professional ethics',
    r.final_score = 0.7017,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6234'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/7814e88f-c133-4c3b-b27f-857afa145d42'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'adversarial thinking; critical evaluation of complex systems; regulatory compliance awareness',
    r.evidence_text = 'Additionally, the course equips students with knowledge of certain provisions of the cybersecurity law and the ACM software engineering code of ethics',
    r.final_score = 0.6591,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6234'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/4134622c-c3fb-4a41-beb6-6d58ba5107db'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'critical evaluation of complex systems; professional accountability; technical documentation skills',
    r.evidence_text = 'Upon completion of the course, students are able to apply the acquired knowledge to deploy and handle situations to ensure system security and safety in accordance with legal principles and professional ethics',
    r.final_score = 0.6510,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6234'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/cdd8b6b2-2fd9-453c-8d62-8a1dc6efcd49'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'critical evaluation of complex systems; strategic planning; systems thinking',
    r.evidence_text = 'Deploy, configure, and evaluate cybersecurity solutions in experimental or simulated environments using appropriate information technology tools and platforms',
    r.final_score = 0.6357,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6234'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/0ffdb6ac-03b5-4f1c-bfcc-3d9cb874fdf9'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'continuous monitoring mindset; ethical decision-making',
    r.evidence_text = 'Upon completion of the course, students are able to apply the acquired knowledge to deploy and handle situations to ensure system security and safety in accordance with legal principles and professional ethics',
    r.final_score = 0.6085,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6234'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/397da142-ab35-48fe-b154-7c38f447adfb'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'systems thinking',
    r.evidence_text = 'Deploy, configure, and evaluate cybersecurity solutions in experimental or simulated environments using appropriate information technology tools and platforms',
    r.final_score = 0.5768,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6234'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/5898d99a-62a4-4e10-a2e3-0d815ce44248'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'critical evaluation of complex systems; incident response planning',
    r.evidence_text = 'Deploy, configure, and evaluate cybersecurity solutions in experimental or simulated environments using appropriate information technology tools and platforms',
    r.final_score = 0.5671,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();


MATCH (c:Course {course_id: 'SC6234'})
MATCH (s:Skill {uri: 'http://data.europa.eu/esco/skill/7f2afce6-e98b-4bbe-8441-d52b45e28ab8'})
MERGE (c)-[r:SUPPORTS_SKILL]->(s)
SET r.support_concept = 'incident response planning; regulatory compliance awareness',
    r.evidence_text = 'Additionally, the course equips students with knowledge of certain provisions of the cybersecurity law and the ACM software engineering code of ethics',
    r.final_score = 0.5210,
    r.review_status = 'accepted',
    r.method = 'LLM-Concept+BM25+FAISS+ESCOXLMR+RRF+MultiSignal',
    r.created_at = timestamp();

